### ISSUE TITLE
linking MKL to numpy to accelerate Numpy functions 

### ISSUE THREAD

**Issue by nw13slx** [mir-group/flare#102]
When the training set grows very big, i. e. >400 atom environments, the numpy functions becomes the rate limiting step, simply because it is not parallelized.

Linking Numpy to MKL and the set environmental variable OMP_NUM_THREADS to the number of cpus can help a lot.

Maybe we should write this to README.

**Comment by stevetorr** [comment]
Apparently, when setting up your conda environment on Odyssey/Cannon, this is as simple as the following three lines performed in sequence: 

`conda update mkl 
conda install mkl-include 
conda install numpy scipy
`
Though I have not tested it exhaustively. One can verify that this was correctly performed by calling

` import numpy
numpy.show_config()
`
And looking for MKL in the list of libraries. However, I have not profiled how this affects or improves performance, or tested this procedure exhaustively.

**Comment by nw13slx** [comment]
I just found that this acceleration also have similar parallel nesting trouble as in #89 . The gp.predict function uses Numpy matmul, while it can be called by multiple threads by predict_on_structure_par in predict.py. This can lead to severe CPU overloading when the number of reference structures exceeds 500.

We need to look into how to switch on/off the MKL acceleration on the flight.
