### ISSUE TITLE
Add option to store DFT runs in another folder during OTF calculation

### ISSUE THREAD

**Issue by stevetorr** [mir-group/flare#122]
For one reason or another, it may be desirable to hold onto the DFT data generated during an OTF run, from the inputs to the outputs (e.g. for VASP, charge density files and wave functions are stored in their own separate files). This is doubly true for expensive DFT calculations for large systems, for which the data may be desirable later.

One way to solve this would be to pass in an argument to OTF which takes a tuple of two elements: the first being a single file, or a list of files to copy to another directory, and the second argument being the directory. If this argument were used, after DFT calls, the files would be copied to the specified folder.

**Comment by McAlexDudu** [comment]
@stevetorr I want to use the 'write_model' parameter, but why said'TypeError: __init__() got an unexpected keyword argument 'write_model''? any suggestion?
