### ISSUE TITLE
Potential energy not calculated

### ISSUE THREAD

**Issue by cganley2** [mir-group/flare#142]
In lines 191-192 of otf.py, self.pred_func is called but local_energies are not returned; thus potential energy is not calculated. I emailed Jonathan earlier and he mentioned adding a local_energies attribute to the structure class and have the predict functions update it.

**Comment by aaronchen0316** [comment]
line 164 in predict.py, `local_energies = np.array([0 for _ in range(structure.nat)])` will force gp.predict_local_energy(chemenv) to int, which gives 0 eV for potential energy.

**Comment by YuuuuXie** [comment]
this has been solved
