### ISSUE TITLE
Possible bug in velocity/KE/T evaluation

### ISSUE THREAD

**Issue by limmaestro** [mir-group/flare#143]
Several velocity components are reported to be ~3 orders of magnitude larger than normal, resulting in unphysically large KE and T.

![Screen Shot 2020-02-21 at 1 46 04 PM](https://user-images.githubusercontent.com/43581567/75062308-90e31580-54b0-11ea-9085-85b1a4c47154.png)
...
![Screen Shot 2020-02-21 at 1 46 24 PM](https://user-images.githubusercontent.com/43581567/75062313-93456f80-54b0-11ea-89d5-9683d6e95a98.png)

If these velocities were true, those atoms would be moving several bond lengths in a timestep, which I do not observe from visualizing the trajectory.  Fortunately I do not think the dynamics is affected by this, at the moment.

In calculate_temperature under md.py:

- Velocities are calculated from x(i+1) and x(i-1), in units of **Ang/ps**

```
velocities = (new_pos -
                  structure.prev_positions) / (2 * dt)
```

- KE is evaluated using atomic quantities, therefore in units of **amu * (Ang/ps)^2**

```
    KE = 0
    for i in range(len(structure.positions)):
        for j in range(3):
            KE += 0.5 * \
                structure.mass_dict[structure.species_labels[i]] * \
                velocities[i][j] * velocities[i][j]
```

- Therefore, when T is evaluated from KE, kb should be in **atomic units** involving amu, Ang, ps, K.  The one given in the code is in eV/K.  See below for derivation of the unit conversion.

amu = g/mol

![kb_conversion](https://user-images.githubusercontent.com/43581567/75061540-ed453580-54ae-11ea-9a5e-54cebe2ac812.jpg)

- However, this unit correction does not address the issue where random velocity components are reported to be ~3 OOM larger than they should be.  The problem started occurring only when I moved over to Odyssey after the branches were reorganized (I reinstalled FLARE from scratch).  The problem did not occur when I was using NERSC.  Both master and development branches give me this problem.

**Comment by nw13slx** [comment]
do you have a small script that can reproduce the problem?

**Comment by limmaestro** [comment]
There was a bug in the way in which I set up the initial position in the beginning.  I will retest and update here.

**Comment by limmaestro** [comment]
After fixing my personal bug in initial structure setup, the issue has been resolved.  All units are correct it seems!  There is no need for any further action.
