### ISSUE TITLE
Option to print hyperparameters directly

### ISSUE THREAD

**Issue by jonpvandermause** [mir-group/flare#147]
In the current implementation, when the hyperparameters of a GP are optimized, an output object needs to be created in order for the progress of the optimization to be recorded; this creates a few extraneous otf files, e.g. otf_run-f.xyz and otf_run-std.xyz.

As a near term fix, the user can be given the option to print the current hyperparameters directly, which is convenient when running simple tests. We'll eventually want to decouple hyperparameter optimization from otf runs entirely, since they're logically distinct.

**Comment by nw13slx** [comment]
just another two options.
1.  generate a parent class for OTF and GPFA that merges all the similar operations. (They have blocks of codes that are almost the same). The parent class has GP member and output member
2. generate a global list of all output instances and let optimization function search the output instance from this global list. But we need to make sure that all the output files properly close at then end of OTF.

**Comment by jonpvandermause** [comment]
Good options, I think 1) is a larger issue, so I'll post it.

Perhaps we can make the output class more flexible, by giving the option to create one specific file?
