### ISSUE TITLE
Serialization and representation (e.g. __str__) methods for various objects

### ISSUE THREAD

**Issue by stevetorr** [mir-group/flare#16]
Methods for serializing certain objects which are passed between models (i.e. atomic environments, structures, etc), or even models themselves, would be useful. The advantage of this over pickled objects is that they can be more human-readable (and I understand that pickled objects have some security risks associated with them). 

One example application is that JSON objects are easily storable in certain database architectures. This might be relevant for e.g. FOOGA in the near future if we want to automate the process of training GP models for different datasets, as this would let us store them more easily.

In my development branch I've done this for the AtomicEnvironment object. There are ways we could standardize this or easily implement it across our codebase (e.g. by using Monty, which has an object type which allows for effortless JSON serialization of different Python objects).

**Comment by jonpvandermause** [comment]
Good idea to serialize, would be nice to be able to print out attributes of the env/struc/gp objects. As for saving and storing entire gp models, pickle.dump(gp_model, gp_file) works well in practice.

**Comment by stevetorr** [comment]
Todo: Look through classes in env, struc, gp, and add representations

**Comment by stevetorr** [comment]
We have solved serialization.
