### ISSUE TITLE
no "mgp" or "mgpf" pair_style in lammps

### ISSUE THREAD

**Issue by aaronchen0316** [mir-group/flare#164]
Hi, in your after-training tutorial, you wrote script to map GP force field to run lammps simulation with "MGP" force field (or "MGPF" ff in test_mgp.py). However, none of these are LAMMPS default or user-package force field. I am wondering how you performed the flare-lammps parsing/simulation? Thank you.

**Comment by YuuuuXie** [comment]
Hi,

We have developed our own pair style, but it's not released yet.

For now, the temporary solution for the users is to use the **serial** executable in Anders’ website,  using the link below:
http://folk.uio.no/anjohan/lmp

The only problem is that you might not be able to run the simulation in a parallel way, so might not be able to go to very large system size.

Very soon we are gonna release our pair style source code, then you can compile your own lammps executable with our mgp pair style included.

**Comment by anjohan** [comment]
> For now, the temporary solution for the users is to use the **serial** executable in Anders’ website,  using the link below:
> http://folk.uio.no/anjohan/lmp

Note that this executable is compiled on and for Ubuntu, and runs on the Travis machines. If the stars align, it may work on yours as well!

**Comment by aaronchen0316** [comment]
Thank you very much! Looking forward to your own pair style code. Best.

**Comment by YuuuuXie** [comment]
close via #215
