### ISSUE TITLE
Last master commit

### ISSUE THREAD

**Issue by YuuuuXie** [mir-group/flare#171]
This is the last commit of the old master branch
9a972151d39e3ce56703b937d35035da70adf436
@jonpvandermause

**Comment by jonpvandermause** [comment]
@YuuuuXie What is the issue?

**Comment by YuuuuXie** [comment]
> @YuuuuXie What is the issue?

Oh, Lixin said it would be better to add a tag to the previous master version, since we just merged the dev branch into master. 

And considering that the APS talk & tutorial might have attracted some users, and people downloaded the master version at that moment, it will be good to keep that version in record (maybe keep a release & docs in readthedocs website), otherwise people will feel misleading with out current (newly-merged) docstrings
