### ISSUE TITLE
OTF parser fails at "Cutoffs: {'twobody': 3.0, 'threebody': 5.0}"

### ISSUE THREAD

**Issue by YuuuuXie** [mir-group/flare#205]
Currently the otf_parser is hard coded for the header like:
```
Cutoffs: [3.0 5.0]
```
while in the new parameter class, the cutoffs become a dictionary
need to fix the compatibility

**Comment by YuuuuXie** [comment]
Also, in ASE OTF, the cell is written as 
```
Cell([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]])
```
which is different from the primitive otf output, i.e.
```
[[1.0 0.0 0.0]
 [0.0 1.0 0.0]
 [0.0 0.0 1.0]]
```
need to address this issue as well

**Comment by YuuuuXie** [comment]
The otf_parser.py is not updated, there are so many places not compatible
related to #10

**Comment by kitpeng11** [comment]
same phase also failed in gp model.

**Comment by YuuuuXie** [comment]
close via #214
