### ISSUE TITLE
MGP Fails to run for isolated atoms

### ISSUE THREAD

**Issue by stevetorr** [mir-group/flare#206]
If you try to make a prediction on an atom that has no neighbors, MGP throws an exception. This is a problem for e.g. adsorbates which have disassociated into a vacuum above a surface.

**Comment by YuuuuXie** [comment]
@stevetorr what kind of error?

Since now in `mapxb.py` (development branch) there's 
```
120         if len(atom_env.bond_array_2) == 0:
121             return f_spcs, vir_spcs, kern, v_spcs, e_spcs
```
in the predict function, I think if the bond_array_2 has length 0, the predict function will return zero values

**Comment by stevetorr** [comment]
The error is an `IndexError` when it tries to access the 0th element of `bond_array_2` downstream in the methods `predict` calls. As a remark, maybe make the `len` check more robust to also check to see if _all_ of the bond arrays are empty, since it's possible in the far future a person could use a 3-body kernel without any 2-body components, at which point the 2-body bond array would be empty (I think).

**Comment by YuuuuXie** [comment]
@stevetorr could you please give me a simple code snippet to reproduce the error? As shown in the comment above, in prediction if the bond_array_2 is empty, the zero values will be directly returned. So I don't think the `bond_array_2[0]` is reached for that case.

If only the 3-body is used, in our current implementation, in `env.py` the `bond_array_3` is always built upon `bond_array_2` (basically build the long bond list `bond_array_2` first, then short list `bond_array_3`). Just in the kernel function, the 2-body array is not used. But it is always saved in the atomic environment no matter what kernel is used.

**Comment by stevetorr** [comment]
@YuuuuXie  fixed this, this no longer happens! Thanks, Yu!

**Comment by YuuuuXie** [comment]
> @YuuuuXie fixed this, this no longer happens! Thanks, Yu!

Ok, that's great!
