### ISSUE TITLE
mgp.py:    raise ValueError(rebuild_dict, newbound_dict, err_str)

### ISSUE THREAD

**Issue by smc-lucky** [mir-group/flare#208]
Recently, I try to use FLARE according to the tutorials "on-the-fly training using ASE",  But  I am in trouble.
     My calculated system is "GeTe" (64-atoms structure), I want to get an accurate potential to run MD with LAMMPS.
     There are a question:
     1.  file "/usr/local/lib/python3.6/dist-packages/flare/mgp/mgp.py", line 213, in predict
          raise ValueError(rebuild_dict, newbound_dict, err_str)

    My part input is as below:
      """
     from flare.ase.calculator import FLARE_Calculator
     flare_calculator = FLARE_Calculator(gp_model,
                                    par = True,
                                    mgp_model = mgp_model,
                                    use_mapping = True)
    super_cell.set_calculator(flare_calculator)
    """

    
    I hold a view that my input might be fault. 
    My input file is attached. 
[flare-research.zip](https://github.com/mir-group/flare/files/4964795/flare-research.zip)

**Comment by YuuuuXie** [comment]
Fixed in #211 , to be merged
