### ISSUE TITLE
why the OTF class in otf.py file does not have the parameter "write_model"?

### ISSUE THREAD

**Issue by McAlexDudu** [mir-group/flare#209]
It's weird that the OTF class in otf.py in flare-master has the parameter "write_model", but afte I install flare, I do not find that parameter in "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flare/otf.py", and get wrong :TypeError: init() got an unexpected keyword argument 'write_model'.

**Comment by McAlexDudu** [comment]
It's weird that the OTF class in otf.py in flare-master has the parameter "write_model", but afte I install flare, I do not find that parameter in "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flare/otf.py", and get wrong :TypeError: __init__() got an unexpected keyword argument 'write_model'.

**Comment by stevetorr** [comment]
Hi McAlexDudu, sorry that you're having troubles with OTF.

If you installed FLARE using `pip install mir-flare`, then you'll be using a release from February which won't have these changes. We'll fix this shortly. In the meantime, if you use `git clone` to clone this repository, then you should be able to access these `OTF` arguments (and a bunch of other UI changes)!

**Comment by McAlexDudu** [comment]
> Hi McAlexDudu, sorry that you're having troubles with OTF.
> 
> If you installed FLARE using `pip install mir-flare`, then you'll be using a release from February which won't have these changes. We'll fix this shortly. In the meantime, if you use `git clone` to clone this repository, then you should be able to access these `OTF` arguments (and a bunch of other UI changes)!

I got it, thank you so much!
