### ISSUE TITLE
How to resume DFT calculation

### ISSUE THREAD

**Issue by McAlexDudu** [mir-group/flare#212]
DFT calculation will get unconverged every now and then, and when this happened, the calculation will stop and we have to restart all over. How to resume? any suggestion?

**Comment by YuuuuXie** [comment]
Currently if you set `write_model` in otf module to 2 or 3, the GP model will be saved automatically, then you can load gp by 
```
gp_model = GaussianProcess.from_file('filename')
```
Also, you can grab the positions of atoms where your calculation was interrupted, save it as an `np.array` of shape `(n_atoms, 3)`, denoted as `previous_pos`.

Then in the otf setup, use
```
my_otf = OTF(prev_pos_init = previous_pos,
             gp = gp_model,
             <other arguments>)
my_otf.curr_step = <your last step number>
my_otf.run()
```

Above is a temporary solution. But we are also considering having a more simple interface for restarting otf, there was an old issue #49 here. We will add it recent days

**Comment by McAlexDudu** [comment]
> Currently if you set `write_model` in otf module to 2 or 3, the GP model will be saved automatically, then you can load gp by
> 
> ```
> gp_model = GaussianProcess.from_file('filename')
> ```
> 
> Also, you can grab the positions of atoms where your calculation was interrupted, save it as an `np.array` of shape `(n_atoms, 3)`, denoted as `previous_pos`.
> 
> Then in the otf setup, use
> 
> ```
> my_otf = OTF(prev_pos_init = previous_pos,
>              gp = gp_model,
>              <other arguments>)
> my_otf.curr_step = <your last step number>
> my_otf.run()
> ```
> 
> Above is a temporary solution. But we are also considering having a more simple interface for restarting otf, there was an old issue #49 here. We will add it recent days

Thanks a lot, I will try it.
