### ISSUE TITLE
Temperature rescale seems doesn't work in the new code

### ISSUE THREAD

**Issue by kitpeng11** [mir-group/flare#217]
Plus it looks like the new code didn't consider the periodic boundary condition when the atoms are moving -- some times an atom with the coord of (0,x,x) moved to (-0.001,x,x) the code takes it as a huge move of the a lattice, resulting in a huge temperature.

**Comment by YuuuuXie** [comment]
Now the temperature is calculated via `previous_positions`, we need to calculate it via velocities. Will be addressed in the next pull request

**Comment by kitpeng11** [comment]
Is it always rescaled by previous_positions? In the new code, it doesn't react to the input keyword.

**Comment by YuuuuXie** [comment]
yes, you can see flare/otf.py the method "update_positions", I think @jonpvandermause is gonna solve this

**Comment by YuuuuXie** [comment]
addressed in 1a1d135
