### ISSUE TITLE
how to confirm the multithreading is correctly setup

### ISSUE THREAD

**Issue by GengSS** [mir-group/flare#219]
Dear flare team,

I am using the flare to train a GP potential for bulk Cu.
I have confirmed that the numpy is linked with MKL by examing the numpy.config(); 
However, when I tried to train GP against an existing AIMD trajectory using the script shown below, I found that the CPU usage is always slow. By using 'top' command, I found only one CPU is used, and the usage is only 100%.
I wonder how to confirm that multithreading is used during the training?

Thank you very much in advance.
Best,

Geng

`
```
from flare.gp import GaussianProcess
from flare.struc import Structure
from ase.io import read, write
from flare.gp_from_aimd import TrajectoryTrainer
from ase.calculators.singlepoint import SinglePointCalculator

images = read("md.traj", index="0::100",format="traj")
trajectory = []
for a in images:
    e=a.get_potential_energy()
    f=a.get_forces()
    a2 = a.copy()
    a2.set_pbc(True)
    a2.set_calculator(SinglePointCalculator(a2,energy=e,forces=f))
    trajectory.append(Structure.from_ase_atoms(a2))

#parallel=True, per_atom_par=False, n_cpus=2
gp = GaussianProcess(kernels=['twobody','threebody'],
                    hyps=[0.01, 0.01, 0.01, 0.01, 0.01],
                    cutoffs = {'twobody':7, 'threebody':6},
                    hyp_labels=['Two-Body Signal Variance','Two-Body Length Scale','Three-Body Signal Variance',
                                'Three-Body Length Scale', 'Noise Variance'],
                    parallel=True, per_atom_par=False, n_cpus=24)

TT = TrajectoryTrainer(frames=trajectory,
                    gp = gp,
                    rel_std_tolerance = 3,
                    abs_std_tolerance=0,
                    pre_train_on_skips=10, verbose='DEBUG', pre_train_atoms_per_element={'Cu':10},train_atoms_per_element={'Cu':100})
TT.run()
```
`

the bash script is,
`
export OMP_NUM_THREAD=24
export MKL_NUM_THREADS=24
python learn_first_model.py
`

**Comment by YuuuuXie** [comment]
First, it should be `OMP_NUM_THREADS` right? There's an "S" at the end

If there's other issue, probably @stevetorr or @nw13slx  knows what's going on with TT and parallelization settings

**Comment by GengSS** [comment]
Hi,
Thanks for your quick reply.
It was indeed a typo, but when I changed it as the correct environment variable, as:
```
export OMP_NUM_THREADS=24
export MKL_NUM_THREADS=24
python learn_first_model.py
```
Still, there is only one CPU is being used,

Geng

**Comment by YuuuuXie** [comment]
> Hi,
> Thanks for your quick reply.
> It was indeed a typo, but when I changed it as the correct environment variable, as:
> 
> ```
> export OMP_NUM_THREADS=24
> export MKL_NUM_THREADS=24
> python learn_first_model.py
> ```
> 
> Still, there is only one CPU is being used,
> 
> Geng

As a temporary solution, maybe try `per_atom_par=True`, and see if the CPU usage goes up

**Comment by GengSS** [comment]
Thanks for your suggestion,

After switching on per_atom_par,
I still do not see the full CPU usage,
Using `top -u USERNAME`

I can only see the output as below (I am expecting 4 CPU are fully occupied).

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
12116 gengsun   20   0  766m 182m  17m R 99.8  0.3   1:24.02 python
11206 gengsun   20   0 15428 1848 1008 R  0.7  0.0   0:03.64 top
12136 gengsun   20   0 15528 1836 1008 S  0.7  0.0   0:00.61 top
 7253 gengsun   20   0 96200 1888  892 S  0.0  0.0   0:00.03 sshd
 7254 gengsun   20   0  105m 2100 1536 S  0.0  0.0   0:00.04 bash
 8663 gengsun   20   0 96204 1932  904 S  0.0  0.0   0:00.25 sshd
 8664 gengsun   20   0  106m 2168 1572 S  0.0  0.0   0:00.19 bash
12087 gengsun   20   0  103m 1536 1232 S  0.0  0.0   0:00.00 bash
12099 gengsun   20   0  761m 245m  86m S  0.0  0.4   0:07.87 python
```

**Comment by nw13slx** [comment]
Hi,

Could you please try to reduce the OMP_THREAD_NUM and n_cpus to smaller number and test it again? Sometimes the multiprocessing library has trouble handling the treads when the number of threads is larger than the number of cpus.

To test whether the parallel environment (mkl setup and etc.) is properly set up in your environment, you could run some very small tests (small GP with only a couple predictions) with n_cpus=1, 2, 3, OMP_THREAD_NUM=1, 2, 3 and see whether there is linear scale up.

Please let us know how this work.

**Comment by GengSS** [comment]
Hi,
Thanks for your suggestion.
I have set up the same number for 
`OMP_NUM_THREADS ` and `n_cpus ` in `GaussianProcess`,
then I ran the training with a small system.

After a few minutes, I use the command `grep "Wall time" gp_from_aimd.out` to check the speed,

The result is surprising. the best efficiency is obtained with OMP_NUM_THREADS=ncpus=1

n(cpu)=1
 grep "Wall time" gp_from_aimd.out
Wall time from start: 74.53 s
Wall time from start: 0.00 s
Wall time from start: 100.67 s
Wall time from start: 0.00 s
Wall time from start: 148.12 s
Wall time from start: 0.00 s


n(cpu)=2
 grep "Wall time" gp_from_aimd.out
Wall time from start: 323.40 s
Wall time from start: 0.00 s
Wall time from start: 421.69 s
Wall time from start: 0.00 s
Wall time from start: 512.07 s
Wall time from start: 0.00 s
Wall time from start: 712.51 s
Wall time from start: 0.00 s
Wall time from start: 1025.59 s
Wall time from start: 0.00 s


n(cpus)=4
 grep "Wall time" gp_from_aimd.out
Wall time from start: 280.33 s
Wall time from start: 0.00 s
Wall time from start: 459.92 s
Wall time from start: 0.00 s
Wall time from start: 652.95 s
Wall time from start: 0.00 s
Wall time from start: 871.00 s
Wall time from start: 0.00 s
Wall time from start: 1094.03 s
Wall time from start: 0.00 s

**Comment by nw13slx** [comment]
ok. It seems that the multiprocessing overhead took over in the tests. Here's a couple more things to try:

1. Just to confirm, are you still using verbose="DEBUG" for TrajectoryTraining? What's the output with "Single frame calculation time"? 
2. When you use "top", do you see four python processes? The parallelization is not very efficient when the number of atomic environments to predict or train is < 2*n_cpus. This is the limitation of the multiprocessing library. There's not much we can do to improve the efficiency. (We are trying to replace the multiprocessing part with better parallelization frameworks, but it won't be released soon.) Nonetheless, even if the total cpu usage is low, there should always be multiple python processes appear in the top result. 
3. If there is only one python process, that may not be a FLARE problem. You can try some simple multiprocessing scripts to check whether you environment set up is really working.
4. If there are four python processes, you can test with a training set size (number of atomic environments) of ~ 3-5*n_cpus to see whether the scaling is better. In the past, I saw pretty good parallelization for 5000+ atomic environments with n_cpus=32.
5. double check the default multiprocessing start method in your python is "fork". Or add "import multiprocessing as mp;     mp.set_start_method('fork')" in your python script.

**Comment by GengSS** [comment]
Thanks for your reply. Here is the details:

> ok. It seems that the multiprocessing overhead took over in the tests. Here's a couple more things to try:
> 
>     1. Just to confirm, are you still using verbose="DEBUG" for TrajectoryTraining? What's the output with "Single frame calculation time"?

I switched it off, but I will do a new test.

>     2. When you use "top", do you see four python processes? The parallelization is not very efficient when the number of atomic environments to predict or train is < 2*n_cpus. This is the limitation of the multiprocessing library. There's not much we can do to improve the efficiency. (We are trying to replace the multiprocessing part with better parallelization frameworks, but it won't be released soon.) Nonetheless, even if the total cpu usage is low, there should always be multiple python processes appear in the top result.

I can only see one python process during the training.

>     3. If there is only one python process, that may not be a FLARE problem. You can try some simple multiprocessing scripts to check whether you environment set up is really working.

I tried following code. Then I use the top command, and it indeed has 3 python processes.
so I though my python environment is correct.
```
import multiprocessing
import time
import numpy as np

def worker(n):
    while True:
       x = np.random.uniform(n)
       y = np.random.uniform(n)
       z = x*y


if __name__ == "__main__":
    p1 = multiprocessing.Process(target = worker, args = (200,))
    p2 = multiprocessing.Process(target = worker, args = (300,))
    p3 = multiprocessing.Process(target = worker, args = (400,))

    p1.start()
    p2.start()
    p3.start()

    print("The number of CPU is:" + str(multiprocessing.cpu_count()))
```

>     4. If there are four python processes, you can test with a training set size (number of atomic environments) of ~ 3-5*n_cpus to see whether the scaling is better. In the past, I saw pretty good parallelization for 5000+ atomic environments with n_cpus=32.
I will try to increase the number of environments, but I feel that the current problem is I do not see multiple python processes.

>     5. double check the default multiprocessing start method in your python is "fork". Or add "import multiprocessing as mp;     mp.set_start_method('fork')" in your python script.

I have confirmed that the start method is 'fork'.

Best,

Geng

**Comment by nw13slx** [comment]
sorry, just remember this. When you run the new test, could you also add n_sample=1 to gp=GaussianProcess(...)

**Comment by GengSS** [comment]
Hi, I have set up n_sample =1
then
I have
with n_cpu = OMP_NUM_THREADS = 1

grep "Single frame calculation time" gp_from_aimd.out 

Single frame calculation time 3.857785224914551
Single frame calculation time 5.3160400390625
Single frame calculation time 6.488309621810913
Single frame calculation time 7.826421022415161
Single frame calculation time 9.135576963424683
Single frame calculation time 10.348716497421265


with n_cpu = OMP_NUM_THREADS = 4

 grep "Single frame calculation time" gp_from_aimd.out

Single frame calculation time 6.132486820220947
Single frame calculation time 5.245823383331299
Single frame calculation time 6.538400411605835
Single frame calculation time 8.085711240768433
Single frame calculation time 9.136773586273193
Single frame calculation time 10.598991870880127
Single frame calculation time 11.986988067626953
Single frame calculation time 12.371276378631592
Single frame calculation time 14.241947889328003
Single frame calculation time 15.533552885055542
Single frame calculation time 17.060043573379517
Single frame calculation time 17.911728382110596

**Comment by nw13slx** [comment]
ok. Good. At least for the early steps, the n_cpus=4 is not performing 4 much worst to n_cpus=1. So my guess is that your multiprocessing is running perfectly fine. It's just that at the beginning phase, each child process is kind of transient and the pool open overhead takes longer time than the actual computing, killing the scaling. Once the training set size grows larger, each child process takes longer time; the n_cpus=4 performance would perform better than n_cpus=1 .

A side note, it may not be your case. Sometimes the default compute environment of SLURM and PBS may not be properly set to let the code to use multiple cpus, like [this post](https://stackoverflow.com/questions/15639779/why-does-multiprocessing-use-only-a-single-core-after-i-import-numpy) on Stackoverflow. You can test their solutions. Or try something like this:

`cores = {i for i in range(mp.cpu_count())}
os.sched_setaffinity(0, cores)`
