### ISSUE TITLE
how to get the trajectory from the quantum espresso md run? 

### ISSUE THREAD

**Issue by kitpeng11** [mir-group/flare#220]
thx

**Comment by anjohan** [comment]
When you've run an AIMD simulation with QE, you can read it using `ase.io.espresso.read_espresso_out`, e.g.

```python
# Read trajectory into ASE Atoms objects
from ase.io.espresso import read_espresso_out
with open("pwscf64.out", "r") as f:
    traj = list(read_espresso_out(f, index=slice(None)))

# Make a list of FLARE structures
struc_traj = []
for step in traj[::-1]:
    struc_traj.append(Structure.from_ase_atoms(step))
    struc_traj[-1].forces = step.get_forces()

TT = TrajectoryTrainer(frames=struc_traj,...)
```

**Comment by kitpeng11** [comment]
Thanks, it works! After this, I typed 
TT.run()
and got the following error. Could you pls help me with it? Thanks! 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-75-07b1d8ad7aa1> in <module>
----> 1 TT.run()
      2 print("Done!")

~/opt/anaconda3/lib/python3.7/site-packages/flare/gp_from_aimd.py in run(self)
    290         if self.verbose >= 3:
    291             print("Commencing run with pre-run...")
--> 292         self.pre_run()
    293 
    294         train_frame = int(len(self.frames) * (1 - self.validate_ratio))

~/opt/anaconda3/lib/python3.7/site-packages/flare/gp_from_aimd.py in pre_run(self)
    204         """
    205 
--> 206         self.output.write_header(self.gp.cutoffs,
    207                                  self.gp.kernel_name,
    208                                  self.gp.hyps,

AttributeError: module 'flare.gp' has no attribute 'cutoffs'

**Comment by kitpeng11** [comment]
Thanks, it works! But I only give 10 frames of DFT calculations and the program doesn't finish running after 30mins. Is it supposed to be time-consuming? Or some of my setting was wrong? Thanks!


from flare import mc_simple, gp, struc, output, predict, util, md, otf, env,\
  otf_parser

import numpy as np
import time
import matplotlib.pyplot as plt
import pickle
from ase.visualize import view
from ase.io.espresso import read_espresso_out
from json import loads
from flare.struc import Structure
from flare.gp_from_aimd import TrajectoryTrainer

with open("./out.md.500K", "r") as f:
    traj = list(read_espresso_out(f, index=slice(None)))

struc_traj = []
for step in traj[::-1]:
    struc_traj.append(Structure.from_ase_atoms(step))
    struc_traj[-1].forces = step.get_forces()

# create a 2+3-body gaussian process object
kernel = mc_simple.two_plus_three_body_mc  # 2+3-body multispecies kernel
kernel_grad = mc_simple.two_plus_three_body_mc_grad  # gradient for optimization
hyps = np.array([0.01, 1.0, 0.001, 1.0, 0.2])  # initial (bad) choice of hyps
cutoffs = np.array([7.0, 5.5])  #  cutoff radii in A
maxiter = 100  # max number of hyperparameter optimziation steps

gp_model = gp.GaussianProcess(kernel, kernel_grad, hyps, cutoffs,
                              maxiter=maxiter)

TT = TrajectoryTrainer(frames=struc_traj,
                    gp = gp_model,
                    rel_std_tolerance = 3,
                    abs_std_tolerance=0,
                    pre_train_on_skips=5)

TT.run()
print("Done!")

**Comment by YuuuuXie** [comment]
you can monitor the log file and see how the training is going on

**Comment by kitpeng11** [comment]
The log file didn't print out anything.

**Comment by YuuuuXie** [comment]
Maybe try `maxiter=10` or 1, I don't know which log file you are looking at, but perhaps the training of gp is not finished so there's no output. But still the output should at least have some information. Could you please check at what step your code got stuck?

**Comment by kitpeng11** [comment]
Thanks, maxier has set to 1. Several files were made during the run: gp_from_aimd-hyps.dat, gp_from_aimd-hyps.dat-bak, gp_from_aimd.out, gp_from_aimd.out-bak. Apart from gp_from_aimd.out, the others are all empty. In gp_from_aimd.out, there are several frames of the following lines:

Adding atom(s) [13, 3, 15, 26, 23, 16, 24, 5, 21, 6, 8, 4, 12, 14, 17, 7, 25, 22, 40, 39, 31, 38, 41, 34, 32, 37, 33, 27, 28, 30, 29, 36, 35, 11, 2, 10, 19, 1, 20, 18, 0, 9] to the training set.
Uncertainties: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
...

No output from the screen.

**Comment by jonpvandermause** [comment]
@kitpeng11 Please see #222, it's possible that the GP is being initialized with too much data.
