### ISSUE TITLE
a small bug in otf_parser.py

### ISSUE THREAD

**Issue by aaronchen0316** [mir-group/flare#221]
from line 179
```
post_frame = block[index + 3 + self.noa :]
extract_global_info(self.cell_list, self.stress_list, self.thermostat, post_frame)
```
`post_frame` includes output from DFT and MD steps because of the slicing and `extract_global_info()` will extract data from both DFT and MD (if DFT exists) and save them to self.MD_only_variables.
 
my temporary fix was adding:
```
if 'Frame' in line:
    break
```
at the end of the `extract_global_info()` so that it executes only once (i.e. the `post_frame` still contains both DFT and MD output). Perhaps you have a better fix.

**Comment by YuuuuXie** [comment]
I'll look into this issue
