### ISSUE TITLE
MemoryError in GP training

### ISSUE THREAD

**Issue by racheallee** [mir-group/flare#222]
Dear developers,

I'm trying to train a GP potential with existing AIMD trajectories, but I got the following error:

MemoryError: Unable to allocate array with shape (1620000, 1620000) and data type float64

A 3x3x3 bcc crystal with 54 Li atoms was used in AIMD simulations. The simulation was done in a NVT thermostat for 50000 steps (time step 2 fs) at 300 K.

Could you please give me some suggestions on how to solve this error ? Or do you have any guidance on the allocation of memory  for different systems?

Thanks.

**Comment by jonpvandermause** [comment]
Hi racheallee,

Could you please post a snippet of the code that triggered the memory error so that we can try to reproduce it?

Thanks,
Jon

**Comment by racheallee** [comment]
Hi Jon,

Here's the code that triggered the error. The structure_list was generated from the vasprun.xml of the AIMD simulations.

from flare.gp import GaussianProcess

gp = GaussianProcess(kernels=['twobody', 'threebody'], hyps=[0.01, 0.01, 0.01, 0.01, 0.01],
                     cutoffs = {'twobody':7, 'threebody':4},
                     hyp_labels=['Two-Body Signal Variance','Two-Body Length Scale','Three-Body Signal Variance',
                                 'Three-Body Length Scale', 'Noise Variance'])

trajectory = structure_list

from flare.gp_from_aimd import TrajectoryTrainer

TT = TrajectoryTrainer(frames=trajectory, gp = gp, rel_std_tolerance = 3, abs_std_tolerance=0,
                       pre_train_on_skips=5)
TT.run()

Thanks !

Racheal

**Comment by jonpvandermause** [comment]
Hi Racheal,

Thanks. Did the error message include a traceback? Could you post that as well? That will help us pinpoint the part of the code that's causing the problem.

Thanks,
Jon

**Comment by racheallee** [comment]
Here's all the error messages I got:

Traceback (most recent call last):
  File "Li-MD.py", line 108, in <module>
    TT.run()
  File "/home/repos/flare/flare/gp_from_aimd.py", line 355, in run
    self.pre_run()
  File "/home/repos/flare/flare/gp_from_aimd.py", line 328, in pre_run
    self.train_gp(max_iter=self.pre_train_max_iter)
  File "/home/repos/flare/flare/gp_from_aimd.py", line 586, in train_gp
    self.gp.train(logger_name=logger_train)
  File "/home/repos/flare/flare/gp.py", line 415, in train
    'maxiter': self.maxiter})
  File "/home/bin/miniconda3/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 600, in minimize
    callback=callback, **options)
  File "/home/bin/miniconda3/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/bin/miniconda3/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 285, in func_and_grad
    f = fun(x, *args)
  File "/home/bin/miniconda3/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 326, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/bin/miniconda3/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 64, in __call__
    fg = self.fun(x, *args)
  File "/home/repos/flare/flare/gp_algebra.py", line 1336, in get_neg_like_grad
    hyps_mask=hyps_mask, n_cpus=n_cpus, n_sample=n_sample)
  File "/home/repos/flare/flare/gp_algebra.py", line 1234, in get_ky_and_hyp
    hyps, kernel_grad, cutoffs, hyps_mask)
  File "/home/repos/flare/flare/gp_algebra.py", line 1170, in get_ky_and_hyp_pack
    k_mat = np.zeros([size1, size2])
MemoryError: Unable to allocate array with shape (1620000, 1620000) and data type float64

Thanks!

**Comment by jonpvandermause** [comment]
Hi Rachael,

Thanks, that's very helpful. Here's what I believe is going on: by setting pre_train_on_skips to 5, you're attempting to train an initial GP model with all forces from every fifth frame of your AIMD trajectory. You have 50,000 frames total, with 54 x 3 = 162 force components per frame, which means that the initial GP model has 10,000 x 162 =1,620,000 labels. When a GP model is trained, a covariance matrix with size equal to the total number of training labels needs to be constructed. And in this case, the covariance matrix is huge! Way too big to be allocated on most machines.

One solution is to significantly increase pre_train_on_skips, e.g. to 25000, so that you only "seed" the training with a couple of frames.

I hope that helps.

Best,
Jon

**Comment by racheallee** [comment]
Hi jon,

Thanks very much for your suggestions.  I've got one more question regarding the "pre_train_on_skips". How does the number of the seeded frames affect the accuracy of the potential ? Do you have any statistics ?

Racheal

**Comment by jonpvandermause** [comment]
Hi Racheal,

The quality of the final potential shouldn't depend much on the choice of initial frames. Models typically converge on a certain error level (typically around 0.1 eV/A for 2+3-body models) once enough data has been added. To understand the amount of data you need, it's often helpful to compute the learning curve of the model, which tells you the mean absolute error on an independent test set with different amounts of data in the training set. For simple single-species materials restricted to a single phase, we often see convergence after 100 or so environments have been added.

The GP from AIMD module is designed to loop over the training structures and automatically choose environments to add to the training set after the initial seed frames have been added, but it looks like our documentation needs to be fleshed out in more detail. To compute the learning curve, I would suggest manually training and testing the GP on your data; see the short tutorial [here](https://flare.readthedocs.io/en/latest/tutorials/prepare_data.html#try-building-gp-from-data) and the documentation for the GP class [here](https://flare.readthedocs.io/en/latest/flare/gp.html).

Good luck, and let us know if you run into any other issues.

Best,
Jon

**Comment by kitpeng11** [comment]
Hi, I have reduced the frames to 10 but still no result comes out and nothing printing on the screen after 30mins. Could you please help me with this? Thanks!

from flare import mc_simple, gp, struc, output, predict, util, md, otf, env,\
  otf_parser

import numpy as np
import time
import matplotlib.pyplot as plt
import pickle
from ase.visualize import view
from ase.io.espresso import read_espresso_out
from json import loads
from flare.struc import Structure
from flare.gp_from_aimd import TrajectoryTrainer

with open("./out.md.500K", "r") as f:
    traj = list(read_espresso_out(f, index=slice(None)))

struc_traj = []
for step in traj[::-1]:
    struc_traj.append(Structure.from_ase_atoms(step))
    struc_traj[-1].forces = step.get_forces()

# create a 2+3-body gaussian process object
kernel = mc_simple.two_plus_three_body_mc  # 2+3-body multispecies kernel
kernel_grad = mc_simple.two_plus_three_body_mc_grad  # gradient for optimization
hyps = np.array([0.01, 1.0, 0.001, 1.0, 0.2])  # initial (bad) choice of hyps
cutoffs = np.array([7.0, 5.5])  #  cutoff radii in A
maxiter = 100  # max number of hyperparameter optimziation steps

gp_model = gp.GaussianProcess(kernel, kernel_grad, hyps, cutoffs,
                              maxiter=maxiter)

TT = TrajectoryTrainer(frames=struc_traj,
                    gp = gp_model,
                    rel_std_tolerance = 3,
                    abs_std_tolerance=0,
                    pre_train_on_skips=5)

TT.run()
print("Done!")

**Comment by jonpvandermause** [comment]
@kitpeng11 How many atoms are in each frame? What happens when you include only a single frame? By the way, in the code you posted, you've set pre_train_on_skips to 5, which is probably too small (see above).

**Comment by kitpeng11** [comment]
I tried to reduce the qe output to 1 time step and change the pre_train_on_skips to a larger number. In the file gp_from_aimd.out, it prints out one frame of :

Adding atom(s) [4, 7, 26, 6, 25, 13, 24, 22, 23, 15, 8, 16, 21, 3, 14, 12, 17, 5, 29, 32, 36, 31, 28, 40, 33, 41, 39, 34, 35, 38, 30, 37, 27, 2, 20, 19, 1, 10, 11, 9, 0, 18] to the training set.
Uncertainties: [[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
...

Then no more printing. But the code runs for ever.
