### ISSUE TITLE
name not found in _global_training_data when in parallel

### ISSUE THREAD

**Issue by bduschatko** [mir-group/flare#223]
This was fixed in the efs_force_vector_unit function in gp_algebra.py, but it is still an issue in force_force_vector_unit

**Comment by YuuuuXie** [comment]
It seems to be the same reason as `efs_force_vector_unit`, basically when `global_training_data` is called in the for loop, there will appear this error, which is extremely weird. It can be addressed in the same way as what has been done in `efs_force_vector_unit`. Will merge it in the next pull request
