### ISSUE TITLE
Bug in how positions are copied to structure 

### ISSUE THREAD

**Issue by bduschatko** [mir-group/flare#232]
Structure positions are getting wrapped positions, causing issues with velocities: 
https://github.com/mir-group/flare/blob/c821e23faef636bfcd8960b6eb7efd7b5e245ccb/flare/md.py#L20
https://github.com/mir-group/flare/blob/c821e23faef636bfcd8960b6eb7efd7b5e245ccb/flare/otf.py#L459

**Comment by jonpvandermause** [comment]
Closed by #255
