### ISSUE TITLE
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD with errorcode 1

### ISSUE THREAD

**Issue by McAlexDudu** [mir-group/flare#235]
Hi, developers! Recently I use mir-flare==0.1.1 and follow the turtorial "On-the-fly aluminum potential". Here is my code:

![2020-09-06 11-59-12 的屏幕截图](https://user-images.githubusercontent.com/16278257/92317907-687bcc80-f038-11ea-9ccc-ff27b4b374ef.png)

and I got error like this:

![2020-09-06 12-00-48 的屏幕截图](https://user-images.githubusercontent.com/16278257/92317948-aa0c7780-f038-11ea-8286-211981479771.png)

I had installed openmpi and quantum espressor.

**Comment by owaisahmad18** [comment]
can you share how did you fixed it?

**Comment by McAlexDudu** [comment]
> can you share how did you fixed it?

Sorry, I didn't remember  it and no longer use mir-flare
