### ISSUE TITLE
How to optimize the hyperparameters?

### ISSUE THREAD

**Issue by kitpeng11** [mir-group/flare#236]
The printed out likelihood is negative after 50 optimization. Is there any way to get a set of good hyperparameters?  Thanks

**Comment by mkrompiec** [comment]
You can try restarting from a different initial guess of hyperparameters. But the most likely reasons are that you don’t have enough training data, or the system can’t be adequately modelled by the kernel you chose.

**Comment by jonpvandermause** [comment]
Hi kitpeng11,

You can interpret the log marginal likelihood as a measure of how well your training data is described by the current model. As mkrompiec notes, a negative likelihood after hyperparameter optimization usually indicates that a more sophisticated model is needed.

Have you tried repeating the optimization with different kernels?

Best,
Jon

**Comment by YuuuXie** [comment]
Close stale issue
