### ISSUE TITLE
no such file or directory : 'srun'

### ISSUE THREAD

**Issue by McAlexDudu** [mir-group/flare#237]
Hi, developers! Recently I use mir-flare==0.1.1 and follow the tutorial "On-the-fly aluminum potential", and I want to use "Acceleration with multiprocessing and MKL", so I configure my code like this:

![2020-09-07 09-25-18 的屏幕截图](https://user-images.githubusercontent.com/16278257/92340450-f9ac7b00-f0ec-11ea-9d29-ce8673392192.png)

but I got something error:

![2020-09-07 09-24-18 的屏幕截图](https://user-images.githubusercontent.com/16278257/92340466-0c26b480-f0ed-11ea-9a97-001fe124634e.png)

**Comment by aaronchen0316** [comment]
in the OTF(), the default to mpi is "srun". I guess you are not running parallel on a slurm managed cluster. Maybe try change it to mpi='mpi' in OTF()

**Comment by anjohan** [comment]
Hi,

Thanks for trying our code!

You probably have to initialize your OTF object with `mpi="mpirun"`. For some reason, the code defaults to running the DFT code with `srun` (which is used on some clusters).

**Comment by McAlexDudu** [comment]
> in the OTF(), the default to mpi is "srun". I guess you are not running parallel on a slurm managed cluster. Maybe try change it to mpi='mpi' in OTF()

Thanks a lot, mpi = 'mpi' works and erros eliminate!

**Comment by McAlexDudu** [comment]
> Hi,
> 
> Thanks for trying our code!
> 
> You probably have to initialize your OTF object with `mpi="mpirun"`. For some reason, the code defaults to running the DFT code with `srun` (which is used on some clusters).

 mpi="mpirun" does not work for me but mpi="mpi" does, thanks for your suggentioin!

**Comment by McAlexDudu** [comment]
> mpi="mpirun" does not work for me but mpi="mpi" does, thanks for your suggentioin!

mpi="mpirun" does not work for me but mpi="mpi" does, thanks for your suggestion!

**Comment by McAlexDudu** [comment]
> Hi,
> 
> Thanks for trying our code!
> 
> You probably have to initialize your OTF object with `mpi="mpirun"`. For some reason, the code defaults to running the DFT code with `srun` (which is used on some clusters).

mpi="mpirun" does not work for me but mpi="mpi" does, thanks for your suggestion!

**Comment by McAlexDudu** [comment]
> Hi,
> 
> Thanks for trying our code!
> 
> You probably have to initialize your OTF object with `mpi="mpirun"`. For some reason, the code defaults to running the DFT code with `srun` (which is used on some clusters).

mpi="mpirun" does not work for me but mpi="mpi" does, thanks for your suggestion!
