### ISSUE TITLE
Error when using the MappedGaussianProcess predict function on an AtomicEnvironment

### ISSUE THREAD

**Issue by ClaudioZeni** [mir-group/flare#240]
After loading a mgp file that was saved in the ".json" format:

> mgp = MappedGaussianProcess.from_dict(filename)

and loading some example structures:

> structures = Structure.from_file("309/flare_structures.json")

this line fails:

> mgp.predict(AtomicEnvironment(structures[0], 0, {"twobody": 8.0, "threebody": 4.5}))

with the following error:

> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-4-1cd8e059ee61> in <module>
>       7 cutoffs = {"twobody": 8.0, "threebody": 4.5}
>       8 
> ----> 9 mgp.predict(AtomicEnvironment(structures[0], 0, cutoffs))
> 
> ~\AppData\Roaming\Python\Python38\site-packages\flare\mgp\mgp.py in predict(self, atom_env)
>     197         for xb in self.maps:
>     198             try:
> --> 199                 pred = self.maps[xb].predict(atom_env)
>     200                 force += pred[0]
>     201                 virial += pred[1]
> 
> ~\AppData\Roaming\Python\Python38\site-packages\flare\mgp\mapxb.py in predict(self, atom_env)
>     108     def predict(self, atom_env):
>     109 
> --> 110         assert Parameters.compare_dict(
>     111             self.hyps_mask, atom_env.cutoffs_mask
>     112         ), "GP.hyps_mask is not the same as atom_env.cutoffs_mask"
> 
> AssertionError: GP.hyps_mask is not the same as atom_env.cutoffs_mask

it appears as the Parameters.compare_dict() function is trying to compare each key in the mgp.maps['twobody'].hyps_mask dictionary but it is unable to find a corresponding key in the atom_env.cutoffs_mask dictionary.

This could be easily bypassed by changing the assertion to a warning, or by updating the way the two dictionaries are compared.

This error occurred using the pip version of flare.

**Comment by YuuuuXie** [comment]
This issue has been addressed in the master branch, but we have not yet updated the pip version with the most recent master, will do it soon

**Comment by ClaudioZeni** [comment]
Good to know, thanks!
