### ISSUE TITLE
How do I train using an ASE trajectory or list of ASE structures?

### ISSUE THREAD

**Issue by mkrompiec** [mir-group/flare#243]
Hi, is it possible to train a model using an ASE trajectory or list of structures (with calculated energies and forces), instead of the OTF method?

**Comment by YuuuuXie** [comment]
Hi, you can take a look at the tutorials:
https://flare.readthedocs.io/en/latest/tutorials/prepare_data.html
https://flare.readthedocs.io/en/latest/tutorials/gpfa.html

**Comment by mkrompiec** [comment]
Oh, right. Thank you. Should have RTFM ;).
