### ISSUE TITLE
Bug: cannot map MGP to an OTF-trained GP

### ISSUE THREAD

**Issue by mkrompiec** [mir-group/flare#246]
When I try to perform OTF learning using an already trained GP and an MGP, the MGP code crashes.

I followed the example from the tutorial:
```
import numpy as np
from ase import units
from ase.spacegroup import crystal
from ase.build import bulk

np.random.seed(12345)

a = 3.52678
super_cell = bulk('C', 'diamond', a=a, cubic=True)
from flare.gp import GaussianProcess
from flare.utils.parameter_helper import ParameterHelper

# set up GP hyperparameters
kernels = ['twobody', 'threebody'] # use 2+3 body kernel
parameters = {'cutoff_twobody': 5.0,
              'cutoff_threebody': 3.5}
pm = ParameterHelper(
    kernels = kernels,
    random = True,
    parameters=parameters
)

hm = pm.as_dict()
hyps = hm['hyps']
cut = hm['cutoffs']
print('hyps', hyps)

gp_model = GaussianProcess(
    kernels = kernels,
    component = 'mc', # If you are using ASE, please set to "mc" no matter for single-component or multi-component
    hyps = hyps,
    cutoffs = cut,
    hyp_labels = ['sig2','ls2','sig3','ls3','noise'],
    opt_algorithm = 'L-BFGS-B',
    n_cpus = 40
)
from flare.ase.calculator import FLARE_Calculator

flare_calculator = FLARE_Calculator(gp_model,
                                    par = True,
                                    mgp_model = None,
                                    use_mapping = False)

super_cell.set_calculator(flare_calculator)
from ase.calculators.lj import LennardJones
lj_calc = LennardJones()
from ase import units
from ase.md.velocitydistribution import (MaxwellBoltzmannDistribution,
                                         Stationary, ZeroRotation)

temperature = 500
MaxwellBoltzmannDistribution(super_cell, temperature * units.kB)
Stationary(super_cell)  # zero linear momentum
ZeroRotation(super_cell)  # zero angular momentum

md_engine = 'VelocityVerlet'
md_kwargs = {}
otf_params = {'init_atoms': [0, 1, 2, 3],
              'output_name': 'otf',
              'std_tolerance_factor': 2,
              'max_atoms_added' : 4,
              'freeze_hyps': 10,
              'write_model': 3} # If you will probably resume the training, please set to 3

test_otf = ASE_OTF(super_cell,
                   timestep = 1 * units.fs,
                   number_of_steps = 50,
                   dft_calc = lj_calc,
                   md_engine = md_engine,
                   md_kwargs = md_kwargs,
                   **otf_params)

test_otf.run()

```
Initially, I thought the issue is related to loading the GP from json, but actually it doesn't matter if you run the following lines or not:
```
gp_model.write_model('lj', format='json')
gp_model = GaussianProcess.from_file('lj.json')
```

I attempted to run OTF training again, this time with an MGP:
```
from flare.mgp import MappedGaussianProcess

grid_params = {'twobody':   {'grid_num': [64]},
               'threebody': {'grid_num': [16, 16, 16]}}

mgp_model = MappedGaussianProcess(grid_params,
                                  unique_species = [6],
                                  n_cpus = 1,
                                  var_map=None)
from flare.ase.calculator import FLARE_Calculator

flare_calculator = FLARE_Calculator(gp_model,
                                    par = True,
                                    mgp_model = mgp_model,
                                    use_mapping = True)

super_cell.set_calculator(flare_calculator)
temperature = 500
MaxwellBoltzmannDistribution(super_cell, temperature * units.kB)
Stationary(super_cell)  # zero linear momentum
ZeroRotation(super_cell)  # zero angular momentum

md_engine = 'VelocityVerlet'
md_kwargs = {}
otf_params = {'init_atoms': [0, 1, 2, 3],
              'output_name': 'otf',
              'std_tolerance_factor': 2,
              'max_atoms_added' : 4,
              'freeze_hyps': 10,
              'write_model': 3} # If you will probably resume the training, please set to 3
from flare.ase.otf import ASE_OTF
test_otf = ASE_OTF(super_cell,
                   timestep = 1 * units.fs,
                   number_of_steps = 50,
                   dft_calc = lj_calc,
                   md_engine = md_engine,
                   md_kwargs = md_kwargs,
                   **otf_params)

test_otf.run()
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-e544d34caa7c> in <module>
     38                    **otf_params)
     39 
---> 40 test_otf.run()

/sw-pmpv/sdk/anaconda-python/2019.10/envs/anaconda-2019.10/lib/python3.7/site-packages/flare/otf.py in run(self)
    242                 # compute forces and stds with GP
    243                 self.dft_step = False
--> 244                 self.compute_properties()
    245 
    246                 # get max uncertainty atoms

/sw-pmpv/sdk/anaconda-python/2019.10/envs/anaconda-2019.10/lib/python3.7/site-packages/flare/ase/otf.py in compute_properties(self)
    187 
    188         if not self.flare_calc.results:
--> 189             self.atoms.calc.calculate(self.atoms)
    190 
    191     def md_step(self):

/sw-pmpv/sdk/anaconda-python/2019.10/envs/anaconda-2019.10/lib/python3.7/site-packages/flare/ase/calculator.py in calculate(self, atoms)
     98 
     99         if self.use_mapping:
--> 100             self.calculate_mgp(atoms)
    101         else:
    102             self.calculate_gp(atoms)

/sw-pmpv/sdk/anaconda-python/2019.10/envs/anaconda-2019.10/lib/python3.7/site-packages/flare/ase/calculator.py in calculate_mgp(self, atoms)
    159             # TODO: Check that stress is being calculated correctly.
    160             try:
--> 161                 f, v, vir, e = self.mgp_model.predict(chemenv)
    162                 self.results["forces"][n] = f
    163                 self.results["partial_stresses"][n] = vir

/sw-pmpv/sdk/anaconda-python/2019.10/envs/anaconda-2019.10/lib/python3.7/site-packages/flare/mgp/mgp.py in predict(self, atom_env)
    198         for xb in self.maps:
    199             try:
--> 200                 pred = self.maps[xb].predict(atom_env)
    201                 force += pred[0]
    202                 virial += pred[1]

/sw-pmpv/sdk/anaconda-python/2019.10/envs/anaconda-2019.10/lib/python3.7/site-packages/flare/mgp/mapxb.py in predict(self, atom_env)
    116             return f_spcs, vir_spcs, kern, v_spcs, e_spcs
    117 
--> 118         en_kernel, cutoffs, hyps, hyps_mask = self.kernel_info
    119 
    120         args = from_mask_to_args(hyps, cutoffs, hyps_mask)

TypeError: cannot unpack non-iterable NoneType object

**Comment by mkrompiec** [comment]
Same error if you try to use a TrajectoryTrainer-trained GP

**Comment by mkrompiec** [comment]
this line was missing:
``mgp_model.build_map(gp_model)
But the code still crashes:
/sw-pmpv/sdk/anaconda-python/2019.10/envs/anaconda-2019.10/lib/python3.7/site-packages/flare/mgp/mapxb.py in search_lower_bound(self, GP)
    592         lower_bound = np.min(upper_bound)
--> 593         for env in _global_training_data[GP.name]:
    594             if len(env.bond_array_2) == 0:
    595                 continue

KeyError: 'default_gp'

Turns out that the dictionary _global_training_data is empty at this point. I am not sure this is relevant to https://github.com/mir-group/flare/issues/223, because running in serial mode (n_cpus=1, parallel=False) doesn't fix it.

**Comment by mkrompiec** [comment]
I found a workaround. A single line, added at the beginning of SingleMapXbody.build_map(self,GP), in flare/mgp/mapxb.py:
` GP.sync_data()`

**Comment by YuuuuXie** [comment]
Thanks for reporting this issue! I'll take a look at it

**Comment by YuuuuXie** [comment]
1. If you want to use MGP in OTF, you need to set `var_map="pca"`, otherwise there won't be uncertainty
2. The tutorial is set up for the training which initially uses MGP. If you've already got a trained GP, and then want to create a MGP, you have to call
```
mgp_model.build_map(gp_model)
```
as shown in [Tutorial-After_training](https://flare.readthedocs.io/en/latest/tutorials/after_training.html#Map-the-GP-force-field-&-Dump-LAMMPS-coefficient-file)
3. As for the `KeyError: 'default_gp'`, could you please check if you are using the latest `pip` version? I think this issue has been addressed. If the latest pip version does not work, could you try our master branch?

**Comment by mkrompiec** [comment]
Thanks for taking the time and for the comments!
I've installed the current development branch but I still get the KeyError:
```
/sw-pmpv/sdk/anaconda-python/2019.10/envs/anaconda-2019.10/lib/python3.7/site-packages/flare/mgp/mapxb.py in _gengrid_inner(self, name, kernel_info, force_block, s, e)
    418 
    419         if force_block:
--> 420             training_data = _global_training_data[name]
    421             kern_type = f"energy_force"
    422         else:

KeyError: 'default_gp'
```

**Comment by YuuuuXie** [comment]
I didn't manage to reproduce this error. But I made a small change in the `development` branch. 
- Could you please try that and see if the issue is solved? 
- Also I'm not sure if you are restarting the training, so when doing the test, could you please start from scratch? (i.e. not from a trained model, or an interrupted training)

**Comment by mkrompiec** [comment]
Thanks, it is fine now.
