### ISSUE TITLE
FLARE_Calculator not compatible with ASE Optimizers

### ISSUE THREAD

**Issue by mkrompiec** [mir-group/flare#247]
To reproduce: start with the LJ carbon example, then:
```
super_cell = bulk('C', 'diamond', a=a, cubic=True)
from flare.ase.atoms import FLARE_Atoms
super_cell=FLARE_Atoms.from_ase_atoms(super_cell)
from ase.optimize import LBFGS
super_cell.set_calculator(flare_calculator)
dyn = LBFGS(super_cell)
dyn.run()

```
Output:
   Step     Time          Energy         fmax
*Force-consistent energies used in optimization.
LBFGS:    0 12:22:29       -5.172973*       0.4814
LBFGS:    1 12:22:29       -5.172973*       0.4814
LBFGS:    2 12:22:29       -5.172973*       0.4814
and so on. Same thing happens with the FIRE optimizer. For some reason, atomic positions are not updated even though the forces are non-zero. Actually, it is even weirder:
```
super_cell.positions
array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

```
The issue is not limited to this toy example, I first noticed it on a reasonably well trained GP.

**Comment by mkrompiec** [comment]
I take this back. It really depends on how close the initial structure is to the training data. If it is far enough, the geometry optimization crashes but if it is very close it runs OK.

**Comment by mkrompiec** [comment]
Actually, it is a real bug. Because of this bit:

```
    def get_property(self, name, atoms=None, allow_calculation=True):
        if name not in self.results.keys():
            if not allow_calculation:
                return None
            self.calculate(atoms)
        return self.results[name]
```
A property is never recalculated if the coordinates change, unless an explicit call to calculate() is made.

**Comment by YuuuuXie** [comment]
Could you please check if the latest `development` branch resolves this issue?

**Comment by mkrompiec** [comment]
Thank you, it does!
