### ISSUE TITLE
Google Colab tutorial crashes

### ISSUE THREAD

**Issue by mkrompiec** [mir-group/flare#248]
ImportError                               Traceback (most recent call last)
<ipython-input-3-9866ff6b60d3> in <module>()
----> 1 from flare import mc_simple, gp, struc, output, predict, util, md, otf, env,  otf_parser
      2 
      3 import numpy as np
      4 import time
      5 import matplotlib.pyplot as plt

ImportError: cannot import name 'mc_simple'

**Comment by jonpvandermause** [comment]
Hi mkrompiec,

Thank you for flagging this. I'm updating the tutorial so that it works with the current master branch. I'll post a note here once it's updated.

Best,
Jon

**Comment by jonpvandermause** [comment]
@mkrompiec,

I've just updated the tutorial. Could you please give it a try and let me know if you run into issues?

Thanks,
Jon

**Comment by mkrompiec** [comment]
Thanks!
