### ISSUE TITLE
some questions about ase-train

### ISSUE THREAD

**Issue by hjh19970102** [mir-group/flare#249]
Dear developers:
    When I have an ase-train , I found the uncertains are always set to zero.
    Uncertainty: [0. 0. 0.]
    Uncertainty: [0. 0. 0.]
    Uncertainty: [0. 0. 0.]
    Uncertainty: [0. 0. 0.]
 ....    .....   .....   .....    .....    .....
    the codes as follows:

import numpy as np
from ase import units
from ase.spacegroup import crystal
from ase.build import bulk

np.random.seed(12345)

a = 3.52678
super_cell = bulk('C', 'diamond', a=a, cubic=True)

from flare.gp import GaussianProcess
from flare.utils.parameter_helper import ParameterHelper

# set up GP hyperparameters
kernels = ['twobody'] # use 2+3 body kernel
parameters = {'cutoff_twobody': 2.8}
pm = ParameterHelper(
    kernels = kernels,
    random = True,
    parameters=parameters
)

hm = pm.as_dict()
hyps = hm['hyps']
cut = hm['cutoffs']
print('hyps', hyps)

gp_model = GaussianProcess(
    kernels = kernels,
    component = 'mc', # If you are using ASE, please set to "mc" no matter for single-component or multi-component
    hyps = hyps,
    cutoffs = cut,
    hyp_labels = ['sig2','ls2','noise'],
    opt_algorithm = 'L-BFGS-B',
    n_cpus = 8
)

from flare.ase.calculator import FLARE_Calculator

flare_calculator = FLARE_Calculator(gp_model,
                                    par = True,
                                    mgp_model = None,
                                    use_mapping = False)

super_cell.set_calculator(flare_calculator)

     from ase.calculators.espresso import Espresso
import os
# set up DFT calculatoqe
qe_input = './C.pwi' # quantum espresso input file
dft_loc = '/home/hjh/q-e-qe-6.6/bin/pw.x'
# ---------------- set up executable ----------------
label = 'C'
input_file = label+'.pwi'
output_file = label+'.pwo'
no_cpus = 8
npool = 8
pw_loc = '/home/hjh/q-e-qe-6.6/bin/pw.x'

# serial
os.environ['ASE_ESPRESSO_COMMAND'] = f'{pw_loc} < {input_file} > {output_file}'

input_data = {'control':   {'prefix': label,
                            'pseudo_dir': './',
                            'outdir': './out',
                            'calculation': 'scf'},
              'system':    {'ibrav': 0,
                            'ecutwfc': 40,
                            'ecutrho': 326},
              'electrons': {'conv_thr': 1.0e-9,
                            'electron_maxstep': 100,
                            'mixing_beta': 0.7}}

# ----------------  pseudo-potentials -----------------
ion_pseudo = {'C': 'C.upf'}

# -------------- create ASE calculator ----------------
dft_calc = Espresso(pseudopotentials=ion_pseudo, label=label,
                    tstress=True, tprnfor=True, nosym=True,
                    input_data=input_data, kpts=(2, 2, 2))

from ase import units
from ase.md.velocitydistribution import (MaxwellBoltzmannDistribution,
                                         Stationary, ZeroRotation)

temperature = 500
MaxwellBoltzmannDistribution(super_cell, temperature * units.kB)
Stationary(super_cell)  # zero linear momentum
ZeroRotation(super_cell)  # zero angular momentum

md_engine = 'VelocityVerlet'
md_kwargs = {}

from flare.ase.otf import ASE_OTF

otf_params = {'init_atoms': [0],
              'output_name': 'otf',
              'std_tolerance_factor': 1,
              'max_atoms_added' : 1,
              'freeze_hyps': 2,
              'write_model': 3} # If you will probably resume the training, please set to 3

test_otf = ASE_OTF(super_cell,
                   timestep = 1 * units.fs,
                   number_of_steps = 25,
                   dft_calc = dft_calc,
                   md_engine = md_engine,
                   md_kwargs = md_kwargs,
                   **otf_params)

test_otf.run()

I would wonder If I have sometings writing unreasonable in the input ?
Could you please give me some solutions to solve the question?
Thank you .

**Comment by YuuuuXie** [comment]
If you look at the column `Std. Dev (ev/A)` in the output file, you can find it's not zero for frames predicted by GP (starting with `-Frame:`), but they are all zero for frames predicted by DFT (starting with `*-Frame:`)

The problem here is only the printing issue, i.e. the predicted uncertainty is correct and GP is trained based on the predicted uncertainty, but we didn't print out the correct value. We will fix this soon
