### ISSUE TITLE
Large, positive hyperparameter likelihood, but still calling DFT every timestep

### ISSUE THREAD

**Issue by cganley2** [mir-group/flare#251]
For a very simple system (4 atoms) on-the-fly training, the hyperparameters are optimizing to a likelihood of ~200. However, even after the optimization, DFT is still being called every single timestep. Doesn't a high likelihood mean that the hyperparameters pretty accurately describe the system, and thus DFT shouldn't be needed as often?

**Comment by YuuuuXie** [comment]
The criteria of calling DFT is "the max uncertainty predicted by GP for the current frame exceeds `std_tolerance * noise`", where `noise` is `gp.hyps[-1]`. see our [tutorial](https://flare.readthedocs.io/en/latest/tutorials/otf.html#Step-3:-Set-up-OTF-MD-Training-Engine)

So you can observe if your data satisfies the condition. It could be
1. the uncertainty is high, indicating your model needs that many data
2. the `std_tolerance` is set to be too low, usually we set it to be O(1), but you can increase it if needed
3. the `noise` is very low, if below 1e-3, there might be overfitting. But a small noise will make the predicted uncertainty also small, so this possibly is not causing the issue of too many DFT calls

**Comment by cganley2** [comment]
Thanks for the response. Can you expand on what you mean when you say you usually set the `std_tolerance` to O(1)? Also, I am noticing that in my hyperparameter optimization cycles, the `noise` is also being optimized. Why does the noise change with optimization?

**Comment by YuuuuXie** [comment]
For example, usually it is set to be `std_tolerance = 1.0` or `2.0`

The noise can be optimized via the log likelihood. In general, it will kind of converge around certain value as the GP is trained on more and more data. For example, when some structures from low temperature are obtained and added to GP training set, you might get noise ~0.05 or so. Then after adding some high T structures, the noise will increase to ~ 0.1 or 0.2.

**Comment by YuuuuXie** [comment]
@cganley2 Does the reply resolve your problem? If it's resolved, I'll close this issue

**Comment by cganley2** [comment]
Yes it does, thank you. I will most likely have more questions in the future.
