### ISSUE TITLE
structure.positions and structure.prev_positions stored in the otf_checkpt.json are the same

### ISSUE THREAD

**Issue by aaronchen0316** [mir-group/flare#269]
**Describe the bug**
The structure.positions and structure.prev_positions are the same if I read the otf model from the checkpoint file. The issue is the same in both OTF and ASE_OTF but OTF results 0K when restarting the run. (I guess ASE_OTF uses ASE calculator so the temperature update is slightly different). 
Not a huge issue since I could rescale the temperature immediately following the restart.
Also, the stopped otf run is due to the Python script timeout on the cluster. Maybe is caused by the abrupt stop of the script?

**To Reproduce**
```
try:
    otf = OTF.from_checkpoint('otf_checkpt.json')
except:
    pass
try:
    otf = ASE_OTF.from_checkpoint('otf_checkpt.json')
except:
    pass
# print(otf.gp.as_dict())
print(otf.structure.prev_positions[:5])
print('----')
print(otf.structure.positions[:5])
```
```
[[ 0.02088668  1.97264135  5.16316156]
 [ 1.6026943   1.04762089  2.66210221]
 [ 0.013344    1.83935662  1.91738988]
 [ 1.66022141  1.02373048  4.58882936]
 [ 0.18622673  1.85697467 10.35994033]]
----
[[ 0.02088668  1.97264135  5.16316156]
 [ 1.6026943   1.04762089  2.66210221]
 [ 0.013344    1.83935662  1.91738988]
 [ 1.66022141  1.02373048  4.58882936]
 [ 0.18622673  1.85697467 10.35994033]]
```

**Expected behavior**
structure.prev_positions should contain the positions from curr_step - 1

**Additional context**
currently using commit: 69abe1898cf29508bdf3d3499b1f7907f880ed57

**Comment by aaronchen0316** [comment]
I also noticed https://github.com/mir-group/flare/issues/261 and my issue https://github.com/mir-group/flare/issues/253 . I didn't pull request ed2afbbfbea2c4312b4849378fa5cfca969d94ad but edited the /ase/calculator.py to have `super().calculate(atoms=atoms, properties=properties, system_changes=system_changes)` as https://github.com/mir-group/flare/issues/261 suggested. 
Using 69abe1898cf29508bdf3d3499b1f7907f880ed57 and with changes to the calculator.py, however, I still see temperature exploding if I restart from checkpoint using ASE_OTF as 1. prev_pos = curr_pos; 2. FLARE calculator doesn't update the GP forces/stds (I printed the average of `max_stds` in `is_std_in_bound()` in `utils/learner.py` and they were constant) 3. the std_in_bound is always true and atoms in the MD proceed with constant velocities.

**Comment by YuuuXie** [comment]
@aaronchen0316 I just found that in our `Structure` class, the `from_dict` method doesn't load the previous positions, which leads to the same arrays for pos and prev_pos when you load from checkpoint. Now it's added. Could you please check with your OTF training and see if it solves your problem? Also if the blowing up issue still exist?

**Comment by aaronchen0316** [comment]
Hi @YuuuXie 
Thank you for the bug fix! Yes it works with otf(). However, if I restart the run with the ase_otf(), the gp_forces are updated if the model doesn't meet the std_in_bound criteria. If the uncertainty < gp's uncertainty, the gp_force doesn't update with new positions after the restart. I tried to add
```
        system_change = super().check_state(atoms)
        print(system_change)
        if system_change:
            print(atoms.calc)
            atoms.calc.reset()
```
before `super.calculate()` in the ase/calculator.py but I couldn't fix the bug. The sample output of the situation that I am referring:

> 2021-01-21 20:52:13.096752
> 
> Number of cpu cores: 24
> Kernel: ['twobody', 'threebody']
> Training points: 564
> Cutoffs: {'twobody': 6.0, 'threebody': 4.0}
> Number of hyperparameters: 5
> Hyperparameter array: [0.22510513 2.61583164 0.01669482 0.31507828 0.02527894]
> sig2: 0.2251051321748932
> ls2: 2.61583163605617
> sig3: 0.01669481927063272
> ls3: 0.315078277226047
> noise: 0.025278942781484084
> 
> Uncertainty tolerance: 2 times noise hyperparameter
> Timestep (ps): 0.001
> Number of frames: 15000
> Number of atoms: 64
> [skipped info]
> Restart: 4390
> 
> Previous positions (A):
> Ga       0.0552    1.9674    5.2393
> Ga       1.4671    0.9779    2.5676
> N       -0.1714    1.9808    1.9721
> N        1.7598    1.0166    4.5747
> [skipped info]
> -Frame: 4390
> Simulation Time:      4.390 ps
> El            Position (A)                    GP Force (ev/A)                   Std. Dev (ev/A)                  Velocities (A/ps)
> Ga       0.0552    1.9674    5.2393        **_0.0503   -0.9943   -1.4707_**        0.0096    0.0092    0.0100        0.1898   -0.2711    3.4547
> Ga       1.4671    0.9779    2.5676       **_-0.0139   -0.1254    0.7581_**        0.0100    0.0094    0.0100        1.5062    2.6002    1.2514
> N       -0.1714    1.9808    1.9721        **_1.0999   -1.1863   -0.3468_**        0.0136    0.0108    0.0107        9.7174   -4.2119   -1.7955
> N        1.7598    1.0166    4.5747       **_-2.0388   -0.7439   -0.4789_**        0.0122    0.0152    0.0092       -9.6989   -2.3913   -3.5435
> [skipped info]
> -Frame: 4394
> Simulation Time:      4.394 ps
> El            Position (A)                    GP Force (ev/A)                   Std. Dev (ev/A)                  Velocities (A/ps)
> Ga       0.0561    1.9652    5.2515        **_0.0503   -0.9943   -1.4707_**        0.0096    0.0092    0.0100        0.2176   -0.8214    2.6406
> Ga       1.4731    0.9882    2.5734       **_-0.0139   -0.1254    0.7581_**        0.0100    0.0094    0.0100        1.4985    2.5308    1.6710
> N       -0.1264    1.9574    1.9630        **_1.0999   -1.1863   -0.3468_**        0.0136    0.0108    0.0107       12.7479   -7.4807   -2.7511
> N        1.7097    1.0029    4.5578       **_-2.0388   -0.7439   -0.4789_**        0.0122    0.0152    0.0092      -15.3165   -4.4410   -4.8630

I will try to reproduce the problem with simpler model so that it will be easier to reproduce.

Again thank you for the help!

**Comment by YuuuXie** [comment]
Could you please send me the otf and dft input files that you are using? I will try to reproduce your bug

**Comment by aaronchen0316** [comment]
Hi @YuuuXie 

The files are too large to share on Github so I shared a Google Drive folder with you.

**Comment by YuuuXie** [comment]
For the issue that GP forces are the same after loading from checkpoint, I found that we should reset the results dict of the ase calculation in `from_dict` but we didn't.

Could you please check the lastest development branch and see if it solves your problem?

**Comment by YuuuXie** [comment]
close via 88efe67e28f2b6a9cb5c6662675aad0209af134d
