### ISSUE TITLE
FLARE_Calculator

### ISSUE THREAD

**Issue by calmbird89** [mir-group/flare#270]
Hello Flare team,

Using the code, I found one problem.
'atoms' was created by reading the vasprun.xml file.

gp_model = GaussianProcess.from_file('test.gp.json')
atoms.set_calculator(FLARE_Calculator(gp_model=gp_model))
force_gp = atoms.get_forces()

../site-packages/flare/predict.py", line 240, in predict_on_structure_efs
local_energies = np.zeros(structure.nat)
AttributeError: 'Atoms' object has no attribute 'nat'

So I added "atoms.nat = len(atoms)"

gp_model = GaussianProcess.from_file('test.gp.json')
atoms.set_calculator(FLARE_Calculator(gp_model=gp_model))
atoms.nat = len(atoms)
force_gp = atoms.get_forces()

then, I got the other error.

../site-packages/flare/env.py", line 91, in __init__
    self.positions = structure.wrapped_positions
AttributeError: 'Atoms' object has no attribute 'wrapped_positions'

How do I fix this?

Thank you for your kind reply in advance.
Best regards,

Joonhee Kang

**Comment by YuuuXie** [comment]
Hi, these issues are because we have our own `flare.struc.Structure` parallel to the `ase.Atoms` for storing atomic structural information. And we have a wrapper to make `Structure` and `Atoms` compatible, which is the `flare.ase.atoms.FLARE_Atoms`. So every time when you want to use GP to predict properties on the `Atoms` object, wrap the atoms into `FLARE_Atoms`
```
from flare.ase.atoms import FLARE_Atoms
flare_atoms = FLARE_Atoms.from_ase_atoms(atoms)
flare_atoms.calc = FLARE_Calculator(gp_model=gp_model)
force_gp = flare_atoms.get_forces()
```

Let me know if you still have problems

**Comment by calmbird89** [comment]
Dear Yu XieNow the code works fine!!Thank you for all your assistance.Joonhee Kang------------------------------------------------------- Joonhee Kang Ph.D.Senior ResearcherPlatform Technology Laboratory Korea Institute of Energy Research (KIER) 152 Gajeong-ro, Yuseong-gu 34129 Daejeon,  Republic of Korea Mobile : +82-(0)10-2502-0582 Office : +82-(0)42-860-3135 E-mail :  j.kang@kier.re.kr




	---------- 원본 메일 ----------
	보낸사람: "Yu Xie" <notifications@github.com>
	받는사람: "mir-group/flare" <flare@noreply.github.com>

	참조: "calmbird89" <j.kang@kier.re.kr>, "Author" <author@noreply.github.com>

	날짜: 2021-01-12 (화) 01:08:24
	제목: Re: [mir-group/flare] FLARE_Calculator (#270)
	
	
 Hi, these issues are because we have our own
  flare.struc.Structure parallel to the
  ase.Atoms for storing atomic structural information. And
  we have a wrapper to make Structure and
  Atoms compatible, which is the
  flare.ase.atoms.FLARE_Atoms. So every time when you want
  to use GP to predict properties on the Atoms object, wrap
  the atoms into FLARE_Atoms
 from flare.ase.atoms import FLARE_Atoms
flare_atoms = FLARE_Atoms.from_ase_atoms(atoms)
flare_atoms.calc = FLARE_Calculator(gp_model=gp_model)
force_gp = flare_atoms.get_forces()

 Let me know if you still have problems
  —You are receiving this because you
  authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
