### ISSUE TITLE
small bug report

### ISSUE THREAD

**Issue by aaronchen0316** [mir-group/flare#285]
**Describe the bug**
1. make otf_parser.py and gp_from_aimd.py to read longer header info.
2. otf.py: std_tolerance is not read correctly after restart from checkpoint because otf param and the variables have different names

I am not quite certain how to contribute to other's repo so I will just copy-paste the link to my fixes when I cloned flare. I hope this is fine.
otf_parser.py: https://github.com/aaronchen0316/flare/commit/680c533617760b10360d8a25876e832c1e121989
gp_from_aimd.py: https://github.com/aaronchen0316/flare/commit/614c2884e316a91fa1e2a13df7eb0ca26d983ab5
otf.py: https://github.com/aaronchen0316/flare/commit/cd322eb7398ce4f045fe99c2261fe1f7841d8f4e

**Comment by aaronchen0316** [comment]
Also, I am afraid that the "`prev_pos_init`" input parameter doesn't work in ASE_OTF. 
`get_structure_from_input(self, prev_pos_init)` simply changes the `self.atoms.prev_positions` to the `prev_pos_init`. However, `update_temperature(self)` calls ASE Atom object's method to get `KE, temperature, velocity`. These properties are calculated using momenta of the ASE Atom object which is 0 (unless using ASE to set velocity distribution).
For now, I think the easy fix can be add these codes at the end of `get_structure_from_input(self, prev_pos_init)`:
```
velocity = (self.atoms.positions - self.atoms.prev_positions) / self.dt # assuming using the same dt when generate previous position
momenta = self.atoms.masses * velocity
self.atoms.set_momenta(momenta)
```

I have **not** tested it at all, just some pseudo code.

**Comment by YuuuXie** [comment]
@aaronchen0316 My apology for the late response. For the fix of the otf_parser, thanks for reporting the fixes. You can open up a pull request with your fixes, and we will review it & merge it if the pull request looks good.

For the problem of `prev_pos_init`, in ASE_OTF it is not used for MD, but just to write the header in the log. To add the velocity for the `atoms`, you can either set it up before inputting it into the `ASE_OTF`, i.e.
```
atoms.set_momenta(...)
my_otf = ASE_OTF(atoms=atoms, ...)
``` 
or you can use the `from_checkpoint` method (check `flare/otf.py`), and then all the information from your last training will be automatically loaded. 

Let me know there's any issue with it.

I'll consider probably adding the `set_momenta` in `get_structure_from_input`

**Comment by aaronchen0316** [comment]
thank you for your explanation!

**Comment by YuuuXie** [comment]
close via #287
