### ISSUE TITLE
Not showing mgp in installed packages

### ISSUE THREAD

**Issue by owaisahmad18** [mir-group/flare#289]
Hi, I am trying to compile lammps with mgp but it is not showing mgp in installed packages even after after copying mgp folder in src and trying make yes-user-mgp. Kindly help.

**Comment by owaisahmad18** [comment]
Hi, I am trying to compile lammps with mgp but it is not showing mgp in installed packages even after after copying mgp folder in src and trying make yes-user-mgp. Kindly help.

**Comment by YuuuXie** [comment]
What files are in your lammps mgp folder? Are they pair_mgp.cpp and pair_mgp.h?

**Comment by owaisahmad18** [comment]
these 4 files pair_mgp.cpp , pair_mgp.h , pair_mgp_kokkos.cpp and pair_mgp_kokkos.h.

**Comment by owaisahmad18** [comment]
I have tried naming it "USER-MGP" and followed the instructions on [](https://flare.readthedocs.io/en/latest/installation/lammps.html) , it did'nt work.

**Comment by YuuuXie** [comment]
> I have tried naming it "USER-MGP" and followed the instructions on https://flare.readthedocs.io/en/latest/installation/lammps.html , it did'nt work.

Hi, @owaisahmad18 

Perhaps you can check:
1. whether the `pair_mgp.cpp` and `pair_mgp.h` are copied into the `/path/to/lammps/src` (automatically when running `make`)
2. if you run `make -j mpi`, then the executable will be `/path/to/lammps/src/lmp_mpi`, you can check if you are calling the correct executable

If it does not work, you can attach your make commands, execute commands, lammps input file and the error message to us.

**Comment by owaisahmad18** [comment]
I have followed the instructions that you mentioned which are the same as in documentation. after "make yes-user-mgp" command for the mgp package , when i am checking for the installed package by "make package-installed" it is not showing any. 

![Screenshot from 2021-08-13 10-38-08](https://user-images.githubusercontent.com/38828004/129307816-0d046102-e3e5-4924-84af-9c54b6e75bf9.png)

**Comment by YuuuXie** [comment]
Hi @owaisahmad18 

I think this is normal. I tried compilation with `make package-installed` printed, there's no information showing up. But the mgp pair style is still installed if you run lammps with input files. 

I checked the lammps src/Makefile. The reason that `make package-installed` does not print the MGP package is that the `USER-MGP` is not listed in its default "PACKUSER" list, which is printed in `package-installed`. Based on line 49-74 of the `src/Makefile`, only those packaged originally in lammps are in the list, and our customized package is not.

**Comment by owaisahmad18** [comment]
Thanks for clarification. I also tried "make -j mpi" in "lammsp/src" and following error pops.
![image](https://user-images.githubusercontent.com/38828004/129374357-21f02434-0cbb-4345-9b45-de998f201f74.png)

**Comment by YuuuXie** [comment]
Hi @owaisahmad18 

if you don't want to compile with kokkos, try removing the "pair_mgp_kokkos.*" files in both `src` and `src/USER-MGP` folders. And then recompiling the code should work.

If you do want to compile with kokkos, then you can follow this:
https://flare.readthedocs.io/en/latest/installation/lammps.html#mpi-openmp-through-kokkos

**Comment by owaisahmad18** [comment]
Hi, please don't close the issue, My system crashed , i'll get back to you soon.

**Comment by owaisahmad18** [comment]
Hi, Thank you very much for your response, after removing "pair_mgp_kokkos.*" compilation was successful.

**Comment by owaisahmad18** [comment]
Hi, The third way to run LAMMPS is using LAMMPS interface it says please set the environment variable $lmp to the executable. In lammps_executable = 'what should i enter here".

**Comment by YuuuXie** [comment]
Hi @owaisahmad18 ,

You can set `export lmp=/path/to/lammps/src/lmp_mpi`. If you compile with `make -j serial` then just change `lmp_mpi` to `lmp_serial`

**Comment by owaisahmad18** [comment]
![image](https://user-images.githubusercontent.com/38828004/129907906-f8b6d883-3cc3-4759-8bf9-0d6ffc8a232c.png)
![image](https://user-images.githubusercontent.com/38828004/129907958-d7a15bad-819b-48b0-a307-291f6ac5427c.png)
kindly point out what am i doing wrong.

**Comment by YuuuXie** [comment]
In python you can use 
```python
coeff_string = .....
lammps_executable = "/path/to/lammps/src/lmp_mpi"
```

The `export` command is not used in python, but in bash. If you do want to set up the environment variable `$lmp` in python, you should do
```
import os
os.environ["lmp"] = "/path/to/lammps/src/lmp_mpi"
coeff_string = .....
lammps_executable = os.environ.get("lmp")
```

**Comment by owaisahmad18** [comment]
![image](https://user-images.githubusercontent.com/38828004/130007362-2616b1b7-ca3b-4625-ba03-a14d0709dd76.png)
tmp.dump is missing.

**Comment by YuuuXie** [comment]
Hi @owaisahmad18 

Please check your .out or .log file after lammps running, to see if any error message is reported there

**Comment by owaisahmad18** [comment]
![image](https://user-images.githubusercontent.com/38828004/130105160-3e598f10-822d-49ce-abc3-eceb2d5981aa.png)

**Comment by YuuuXie** [comment]
This indicates that your potential file is not read correctly. The reasons could be
1. the potential file name/path is wrong such that the potential is not found by lammps, 
2. the potential file is empty.

**Comment by owaisahmad18** [comment]
I checked potential path is correct and the potential file is not empty. I was able to run the same potential file separately using lammps but i want to run the code using flare interface, which is exactly where i am facing the issue.

**Comment by YuuuXie** [comment]
Then it should be mostly the path issue. Maybe use the absolute path of the potential file in the `pair_coeff`

**Comment by owaisahmad18** [comment]
![image](https://user-images.githubusercontent.com/38828004/130110387-19abe824-b2a4-47c1-bd34-fed054dec908.png)
it is generated in the same directory and assigned to lammps_location variable. 

![image](https://user-images.githubusercontent.com/38828004/130110553-94b76970-7516-4eee-9a32-234c2242eb6d.png)
same variable lammps_location is referred in this part of code.

**Comment by YuuuXie** [comment]
yes, the potential file is generated in the current directory, but depending on your script, the lammps might not be executed in the current directory. For example, the ase lammps calculator usually runs in a different folder

**Comment by owaisahmad18** [comment]
Actually No, as i running code from the test folder in flare which contains all the jupyter notebook necessary

**Comment by YuuuXie** [comment]
Ok, now I see the issue. Thanks for pointing this out. it should be
```
coeff_string = '* * {} Ag I yes yes'.format(lammps_localtion + ".mgp")
```

We'll update it in the tutorial

**Comment by owaisahmad18** [comment]
I tried ase lammps calculator as well , it is not showing any error but it is simply creating a folder by name tmp and copying the potential file in it. i don't see  any output file.
just to be sure kindly check whether i have done this correctly or not as in ase lammps calculator it also asked for lammps executable so i did the same what i did for flare interface method.
![image](https://user-images.githubusercontent.com/38828004/130113909-59dc90f3-b38b-4a8b-9dbe-7e6b5c4f3c0e.png)

**Comment by YuuuXie** [comment]
For this one, as I said previously (quote below), you should set `command` directly to the path
```
parameters = {"command": "/home/xxx/lmp_mpi"
...
```

Or you can set the environment variable first, and point the `command` to the environment variable
```
os.environ["lmp"] = "/path/to/lammps/src/lmp_mpi"
parameters = {"command": os.environ.get("lmp")
...
```

These two are pretty much equivalent


> In python you can use
> 
> ```python
> coeff_string = .....
> lammps_executable = "/path/to/lammps/src/lmp_mpi"
> ```
> 
> The `export` command is not used in python, but in bash. If you do want to set up the environment variable `$lmp` in python, you should do
> 
> ```
> import os
> os.environ["lmp"] = "/path/to/lammps/src/lmp_mpi"
> coeff_string = .....
> lammps_executable = os.environ.get("lmp")
> ```

**Comment by owaisahmad18** [comment]
OK, no error but no output as well

**Comment by YuuuXie** [comment]
You mean in the `tmp` folder, there are no other files except the potential file?

**Comment by owaisahmad18** [comment]
yes exactly. no output lammps file

**Comment by YuuuXie** [comment]
Oh yes, I just realize in the tutorial notebook, there's no calculation done. It only sets up the lammps calculator. If you do want to run calculation, you should define an ase atoms and attach the calculator to it.

```
from ase import Atoms

# create test structure
species = otf_object.gp_species_list[-1]
positions = otf_object.position_list[-1]
forces = otf_object.force_list[-1]
otf_cell = otf_object.header['cell']
structure = Atoms(species, otf_cell, positions)
structure.calc = lmp_calc
structure.get_potential_energy()
```

You can learn more from this tutorial: https://wiki.fysik.dtu.dk/ase/ase/calculators/calculators.html

**Comment by owaisahmad18** [comment]
Hi, the part you have shared above does'nt make any sense with the existing part in tutorial. can u take a look, please.

![image](https://user-images.githubusercontent.com/38828004/130190569-2ea8a7ba-4008-4b07-8ddb-f9ebb165c5df.png)

**Comment by owaisahmad18** [comment]
![image](https://user-images.githubusercontent.com/38828004/130193575-a0b5f27b-db38-433d-b9e0-3d5a52d95047.png)

**Comment by YuuuXie** [comment]
Changing
```
structure = Atoms(species, otf_cell, positions)
```
to
```
structure = Atoms(symbols=species, cell=otf_cell, positions=positions)
```
should work

**Comment by owaisahmad18** [comment]
![image](https://user-images.githubusercontent.com/38828004/130251195-36cc9054-2b29-41a1-a511-a218d4c7fe3d.png)

**Comment by YuuuXie** [comment]
Hi @owaisahmad18 ,

I tried running the tutorial with calculating energy, but didn't get any error. Did you use your own atoms settings? Have you tried "Restart" and then run all cells?

**Comment by owaisahmad18** [comment]
No i am just running the ase part from your code with the changes you suggested.

**Comment by YuuuXie** [comment]
Hi @owaisahmad18 

Since I can not reproduce your error, everything is working in my end, could you attach your complete script, and lammps data files?

Below is what works for me, which should be the same as the tutorial, in case you want to compare with your code

```python
#!/usr/bin/env python
# coding: utf-8

# # After Training
# 
# After the on-the-fly training is complete, we can play with the force field we obtained. 
# We are going to do the following things:
# 
# 1. Parse the on-the-fly training trajectory to collect training data
# 2. Reconstruct the GP model from the training trajectory
# 3. Build up Mapped GP (MGP) for accelerated force field, and save coefficient file for LAMMPS
# 4. Use LAMMPS to run fast simulation using MGP pair style
# 
# ## Parse OTF log file
# 
# After the on-the-fly training is complete, we have a log file and can use the `otf_parser` module to parse the trajectory. 

# In[1]:


import numpy as np
from flare import otf_parser

logdir = '../../../tests/test_files'
file_name = f'{logdir}/AgI_snippet.out'
hyp_no = 2 # use the hyperparameters from the 2nd training step
otf_object = otf_parser.OtfAnalysis(file_name)


# ## Construct GP model from log file
# 
# We can reconstruct GP model from the parsed log file (the on-the-fly training trajectory). Here we build up the GP model with 2+3 body kernel from the on-the-fly log file. 

# In[2]:


gp_model = otf_object.make_gp(hyp_no=hyp_no)
gp_model.parallel = True
gp_model.hyp_labels = ['sig2', 'ls2', 'sig3', 'ls3', 'noise']

# write model to a binary file
gp_model.write_model('AgI.gp', format='json')


# The last step `write_model` is to write this GP model into a binary file, 
# so next time we can directly load the model from the pickle file as

# In[3]:


from flare.gp import GaussianProcess

gp_model = GaussianProcess.from_file('AgI.gp.json')


# ## Map the GP force field & Dump LAMMPS coefficient file
# 
# To use the trained force field with accelerated version MGP, or in LAMMPS, we need to build MGP from GP model. 
# Since 2-body and 3-body are both included, we need to set up the number of grid points for 2-body and 3-body in `grid_params`.
# We build up energy mapping, thus set `map_force=False`.
# See [MGP tutorial](https://flare.readthedocs.io/en/latest/tutorials/mgp.html) for more explanation of the MGP settings.

# In[4]:


from flare.mgp import MappedGaussianProcess

grid_params = {'twobody':   {'grid_num': [64]}, 
               'threebody': {'grid_num': [20, 20, 20]}}

data = gp_model.training_statistics
lammps_location = 'AgI_Molten'

mgp_model = MappedGaussianProcess(grid_params, data['species'], 
    var_map=None, lmp_file_name='AgI_Molten', n_cpus=1)
mgp_model.build_map(gp_model)


# The coefficient file for LAMMPS mgp pair_style is automatically saved once the mapping is done. 
# Saved as `lmp_file_name`. 
# 
# ## Run LAMMPS with MGP pair style
# 
# With the above coefficient file, we can run LAMMPS simulation with the mgp pair style. 
# First download our mgp pair style files, compile your lammps executable with mgp pair style following our [instruction](https://flare.readthedocs.io/en/latest/installation/lammps.html) in the *Installation* section.
# 
# 1. One way to use it is running `lmp_executable < in.lammps > log.lammps` 
# with the executable provided in our repository. 
# When creating the input file, please note to set
# 
# ```
# newton off
# pair_style mgp
# pair_coeff * * <lmp_file_name> <chemical_symbols> yes/no yes/no
# ```
# 
# An example is using coefficient file `AgI_Molten.mgp` for AgI system, 
# with two-body (the 1st `yes`) together with three-body (the 2nd `yes`).
# 
# ```
# pair_coeff * * AgI_Molten.mgp Ag I yes yes
# ```
# 
# 2. Another way is to use the ASE LAMMPS interface

# In[7]:


import os
from flare.utils.element_coder import _Z_to_mass, _element_to_Z
from flare.ase.calculator import FLARE_Calculator
from ase.calculators.lammpsrun import LAMMPS

from ase import Atoms

# create test structure
species = otf_object.gp_species_list[-1]
positions = otf_object.position_list[-1]
forces = otf_object.force_list[-1]
otf_cell = otf_object.header['cell']
structure = Atoms(symbols=species, cell=otf_cell, positions=positions)

# get chemical symbols, masses etc.
species = gp_model.training_statistics['species']
specie_symbol_list = " ".join(species)
masses=[f"{i} {_Z_to_mass[_element_to_Z[species[i]]]}" for i in range(len(species))]

# set up input params
parameters = {'command': os.environ.get('lmp'), # set up executable for ASE
              'newton': 'off',
              'pair_style': 'mgp',
              'pair_coeff': [f'* * {lammps_location + ".mgp"} {specie_symbol_list} yes yes'],
              'mass': masses}
files = [lammps_location + ".mgp"]

# create ASE calc
lmp_calc = LAMMPS(label=f'tmp_AgI', keep_tmp_files=True, tmp_dir='./tmp/',
        parameters=parameters, files=files, specorder=species)

structure.calc = lmp_calc

# To compute energy, forces and stress
energy = structure.get_potential_energy()
print("Energy", energy)
# forces = structure.get_forces()
# stress = structure.get_stress()


# 3. The third way to run LAMMPS is using our LAMMPS interface, please set the
# environment variable `$lmp` to the executable.

# In[6]:


from flare import struc
from flare.lammps import lammps_calculator

# lmp coef file is automatically written now every time MGP is constructed

# create test structure
species = otf_object.gp_species_list[-1]
positions = otf_object.position_list[-1]
forces = otf_object.force_list[-1]
otf_cell = otf_object.header['cell']
structure = struc.Structure(otf_cell, species, positions)

atom_types = [1, 2]
atom_masses = [108, 127]
atom_species = [1, 2] * 27

# create data file
data_file_name = 'tmp.data'
data_text = lammps_calculator.lammps_dat(structure, atom_types,
                                         atom_masses, atom_species)
lammps_calculator.write_text(data_file_name, data_text)

# create lammps input
style_string = 'mgp'
coeff_string = '* * {} Ag I yes yes'.format(lammps_location)
lammps_executable = '$lmp'
dump_file_name = 'tmp.dump'
input_file_name = 'tmp.in'
output_file_name = 'tmp.out'
input_text =     lammps_calculator.generic_lammps_input(data_file_name, style_string,
                                           coeff_string, dump_file_name)
lammps_calculator.write_text(input_file_name, input_text)

# To run lammps and get forces
# lammps_calculator.run_lammps(lammps_executable, input_file_name,
#                              output_file_name)

# lammps_forces = lammps_calculator.lammps_parser(dump_file_name)
```

**Comment by owaisahmad18** [comment]
Actually the script is same as posted above, Thanks for your response anyway ,as i will be running potential with lammps only. One final request as i am new with ASE if you could suggest what changes should i make to 
'''''''''''
a = 3.628
super_cell = bulk('Cu','fcc',a=a,cubic=True)
jitter_factor = 0.1
for atom_pos in super_cell.positions:
    for coord in range(3):
        atom_pos[coord] += (2 * np.random.rand() - 1) * jitter_factor
'''''''''''''
to this script so that i can train the model for alloy systems such as Fe-Ni.

**Comment by YuuuXie** [comment]
Hi @owaisahmad18 

Sorry for the late response. For the alloy system, you might build a single-metal object, and then replace some of the `symbols` by another metal. Then you build up a supercell with the corresponding atoms changed chemical species, but keep the same positions

**Comment by owaisahmad18** [comment]
> Sorry for the late response. For the alloy system, you might build a single-metal object, and then replace some of the `symbols` by another metal. Then you build up a supercell with the corresponding atoms changed chemical species, but keep the same positions

Hi, i was not able to find any command to remove atoms or replace atoms with other symbol in ASE, can you please be more specific.

**Comment by YuuuXie** [comment]
> > Sorry for the late response. For the alloy system, you might build a single-metal object, and then replace some of the `symbols` by another metal. Then you build up a supercell with the corresponding atoms changed chemical species, but keep the same positions
> 
> Hi, i was not able to find any command to remove atoms or replace atoms with other symbol in ASE, can you please be more specific.

Hi @owaisahmad18 

```python
>>> from ase import Atoms
>>> import numpy as np
>>> atoms = Atoms(symbols="C2", positions=np.random.rand(2,3), cell=np.eye(3))
>>> list(atoms.symbols)
['C', 'C']
>>> atoms.symbols[0] = "H"
>>> list(atoms.symbols)
['H', 'C']
```

In this way you change the first atom from carbon to hydrogen

**Comment by owaisahmad18** [comment]
Thanks , I tried setting flare calculator, did'nt worked , plz take a look
![image](https://user-images.githubusercontent.com/38828004/146314924-5466fce6-2656-4d2a-a515-ae0db60533b7.png)

**Comment by owaisahmad18** [comment]
Thanks it worked.
I am working on a Fe-Cu potential, as iron is magnetic how should i include magnetic property of iron, the dft script i was using as follows, should i include the magnetisation in this script or someplace else. please help.
import os
from ase.calculators.espresso import Espresso

# ---------------- set up executable ----------------
label = 'Fe-Cu'
input_file = label+'.pwi'
output_file = label+'.pwo'
no_cpus = 4
npool = 4
pw_loc = '/home/owais/Downloads/q-e-qe-6.8/PW/src/pw.x'

# serial
# os.environ['ASE_ESPRESSO_COMMAND'] = f'{pw_loc} < {input_file} > {output_file}'

## parallel qe using mpirun
os.environ['ASE_ESPRESSO_COMMAND'] = f'mpirun -np {no_cpus} {pw_loc} -npool {npool} < {input_file} > {output_file}'

## parallel qe using srun (for slurm system)
# os.environ['ASE_ESPRESSO_COMMAND'] = 'srun -n {no_cpus} --mpi=pmi2 {pw_loc} -npool {npool} < {input_file} > {output_file}'


# -------------- set up input parameters --------------
input_data = {'control':   {'prefix': label,
                            'pseudo_dir': './',
                            'outdir': './out',
                            'calculation': 'scf'},
              'system':    {'ibrav': 0 ,
                            'ecutwfc': 30,
                            'ecutrho': 150,
                            'occupations': 'smearing',
                           'degauss': 0.01},
              'electrons': {
                            'electron_maxstep': 100,
                            'mixing_beta': 0.5}}

# ----------------  pseudo-potentials -----------------
ion_pseudo = {'Fe': 'Fe.pbe-nd-rrkjus.UPF', 'Cu': 'Cu.pbe-dn-kjpaw_psl.1.0.0.UPF'}

# -------------- create ASE calculator ----------------
dft_calc = Espresso(pseudopotentials=ion_pseudo, label=label,
                    tstress=True, tprnfor=True, nosym=True,
                    input_data=input_data, kpts=(5, 5, 5))

**Comment by owaisahmad18** [comment]
Thanks a lot

**Comment by owaisahmad18** [comment]
Thanks a lot it worked. as i am trying to work with iron and copper, i need to start magnetization for iron specifically. but it says OrderedDict muted during operation. do i need to write starting_magnetization differently?
import os
from ase.calculators.espresso import Espresso

# ---------------- set up executable ----------------
label = 'Fe-Cu'
input_file = label+'.pwi'
output_file = label+'.pwo'
no_cpus = 4
npool = 4
pw_loc = '/home/owais/Downloads/q-e-qe-6.8/PW/src/pw.x'

# serial
# os.environ['ASE_ESPRESSO_COMMAND'] = f'{pw_loc} < {input_file} > {output_file}'

## parallel qe using mpirun
os.environ['ASE_ESPRESSO_COMMAND'] = f'mpirun -np {no_cpus} {pw_loc} -npool {npool} < {input_file} > {output_file}'

## parallel qe using srun (for slurm system)
# os.environ['ASE_ESPRESSO_COMMAND'] = 'srun -n {no_cpus} --mpi=pmi2 {pw_loc} -npool {npool} < {input_file} > {output_file}'


# -------------- set up input parameters --------------
input_data = {'control':   {'prefix': label,
                            'pseudo_dir': './',
                            'outdir': './out',
                            'calculation': 'scf'},
              'system':    {'ibrav': 0 ,
                            'ecutwfc': 40,
                            'ecutrho': 200,
                            'starting_magnetization(2)': 1,
                            'nspin': 2,
                            'occupations': 'smearing',
                           'degauss': 0.01},
              'electrons': {
                            'electron_maxstep': 100,
                            'mixing_beta': 0.25}}

# ----------------  pseudo-potentials -----------------
ion_pseudo = {'Cu': 'Cu.pbe-dn-kjpaw_psl.1.0.0.UPF','Fe': 'Fe.pbe-nd-rrkjus.UPF'}

# -------------- create ASE calculator ----------------
dft_calc = Espresso(pseudopotentials=ion_pseudo, label=label,
                    tstress=True, tprnfor=True, nosym=True,
                    input_data=input_data, kpts=(5, 5, 5))

**Comment by owaisahmad18** [comment]
Thanks a lot
