### ISSUE TITLE
opt_algorithm overwritten when initializing a GaussianProcess

### ISSUE THREAD

**Issue by Sanderosta** [mir-group/flare#298]
Hi developers,

When initializing a GaussianProcess, the GaussianProcess.backward_attributes() function is called. This will check for the presence of 'optimization_algorithm', and if not present subsequently overwrites the manually entered 'opt_algorithm' argument with 'L-BFGS-B'. This makes it impossible to manually enter a different optimization algorithm (even though only L-BFGS-B and BFGS are supported currently if I'm correct.)

Thank you!

**Comment by YuuuXie** [comment]
Hi @Sanderosta , thanks for reporting this issue! I checked the code, this should be a bug. We will fix it soon
