### ISSUE TITLE
Calculation of stresses with DFT

### ISSUE THREAD

**Issue by Sanderosta** [mir-group/flare#301]
**Is your feature request related to a problem? Please describe.**
When using the ASE_OTF() class, the run_dft_par() function in the ase.dft module always requests forces, energies, and stresses. However, for some DFT calculators calculation of stresses can take a significant amount of time. Additionally, this restricts training to periodic structures.

**Describe the solution you'd like**
It would be nice to have the option to pass an argument like "properties" as part of **dft_kwargs to the function, which would then be taken into account when requesting properties. This could save time when stresses are not used by the MD engine.

**Describe alternatives you've considered**
I could create my own ase.dft module, which would not be too much work. However, this would not be an ideal solution.

**Comment by YuuuXie** [comment]
close by #324
