### ISSUE TITLE
Applied pressure using DFT but not showing in generated quantum espresso input file under "cells" tag

### ISSUE THREAD

**Issue by owaisahmad18** [mir-group/flare#305]
I have checked with ASE interface document, the input script is correct but somehow pressure values under "Cells" tag are not adding to the generated input .pwi file, "cell" tag is blank in generated .pwi file. please help.

quantum espresso input script part is below

![image](https://user-images.githubusercontent.com/38828004/156120839-9512fa67-efe1-4fa5-99bc-4de81b994ebb.png)

**Comment by YuuuXie** [comment]
Hi @owaisahmad18 

Apology for the late reply, we were at a conference previously. For your input_data, you need to use "cell" instead of "cells", and then the press parameters will appear in the pwi file.

I'll close this issue as resolved
