### ISSUE TITLE
MGP without KOKKOS 

### ISSUE THREAD

**Issue by dft4py** [mir-group/flare#307]
**Describe the bug**
Is it possible to compile the MGP plugin without KOKKOS?  

**To Reproduce**
Starting from a clean Ubuntu installation, I download LAAMPS from the github, move the mgp files to the /src/ directory of lamps and run cmake.  

First I get an error about pair_mgp_kokkos not being able to find pair_kokkos.h, which makes sense since I have not installed KOKKOS.  If I remove this file then the installation proceeds normally again but when the mgp_pair.cpp file tries to compile I get an error about a protected member.

pair.mgp.cpp:934:33: error "int LAMMPS_NS::NeighREquest::half" is protected within this context

**Comment by anjohan** [comment]
Hi,

Your final error comes from a change in the LAMMPS neighbor API that we haven't incorporated yet. For the time being, you can use a slightly older version, e.g. the git tag `stable_29Sep2021_update2`.
