### ISSUE TITLE
Failed to read gp_model created by OTF module

### ISSUE THREAD

**Issue by hhlim12** [mir-group/flare#309]
**Describe the bug**
When the OTF learning is completed, the gp model in json format is created. 
Problem occur when I load this json file (e.g., `otf_flare.json`) using

```
from flare.gp import GaussianProcess
gp_model = GaussianProcess.from_file('otf_flare.json')
```
see also the error message below.

I noticed that this is due to different structure in the json file. Below is the snapshot of the `otf_flare.json`
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/77390746/171352522-a2aa2d6f-2702-48b9-b61d-959032a1829c.png">

When I rearrange the keys like this, it runs successfully. It seems only the `gp_model` key is necessary in the json file.
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/77390746/171353243-4ef8027e-c8b4-4922-886f-28250999bca1.png">

**To Reproduce**
Get the gp model using OTF learning with `write_model = 3`. Then, read again the gp model using `GaussianProcess.from_file`. I use the same input script as in https://github.com/mir-group/flare/issues/308#issue-1255210103

**Expected behavior**
The gp model can be loaded successfully.

**Screenshots**
Error message:
```
Traceback (most recent call last):
  File "restart_calc.py", line 4, in <module>
    gp_model = GaussianProcess.from_file(sys.argv[1])
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/gp.py", line 1249, in from_file
    gp_model = GaussianProcess.from_dict(json.loads(f.readline()))
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/gp.py", line 941, in from_dict
    GaussianProcess.backward_attributes(dictionary)
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/gp.py", line 1398, in backward_attributes
    if not isinstance(dictionary["cutoffs"], dict):
KeyError: 'cutoffs'
```
**Additional context**
I install the FLARE by cloning this repo.

**Comment by YuuuXie** [comment]
Hi @hhlim12 , I think the `otf_flare.json` is for `flare.ase.calculator.FLARE_Calculator` instead of `flare.gp.GaussianProcess`. Let me know if that works or not.

**Comment by hhlim12** [comment]
@YuuuXie, Thank you for the reply!. Yes you're right. So the `otf_flare.json` is for FLARE_calculator _that contain GP model_. I thought it was a GP model itself. Now this code can be run successfully.
```
from flare.ase.calculator import FLARE_Calculator

flare_calculator = FLARE_Calculator.from_file('otf_flare.json')
```

Sorry for my mistake.

Best,

Harry
