### ISSUE TITLE
Energies obtained with colab workbook example seem inconsistent

### ISSUE THREAD

**Issue by ThePauliPrinciple** [mir-group/flare#311]
**Describe the bug**
The energies obtained with colab example workbook https://colab.research.google.com/drive/1VzbIPmx1z-uygKstOYTj2Nqr53AMC5NL?usp=sharing seem inconsistent with the forces.

![cor](https://user-images.githubusercontent.com/35560762/182567861-d5a1b287-193f-41f8-8189-42ea29eb901b.png)

For some reason the energies that I obtain from FLARE to do not correlate correctly to the reference values. Considering that the scatter plot here still has all points on a line (but with a slope different from 1) it seems like a systematic error. It is not clear to me whether I am using the values I obtain incorrectly (misunderstanding what they mean) or whether this is an actual bug in FLARE.

**To Reproduce**
Run the notebook as is, then add the following cell to obtain the image above:

```python
import numpy as np

energy_correlation = []
force_correlation = []
sgp_calc = SGP_Calculator(sparse_gp)
for atoms in all_structures:
    sgp_calc.calculate(atoms)
    atoms.calc.calculate(atoms)
    energy_correlation.append((atoms.calc.results['energy'],sgp_calc.results['energy']))
    for force_calc, force_sgp in zip(atoms.calc.results['forces'],sgp_calc.results['forces']):
        force_correlation.append((force_calc, force_sgp))
energy_correlation = np.array(energy_correlation)
force_correlation = np.array(force_correlation)

import matplotlib.pyplot as plt

fig, axs = plt.subplots(1,2,figsize=(7,7))
for ax, correlation,title in zip(axs, [energy_correlation, force_correlation],['energy','force']):
    ax.scatter(correlation[:,0], correlation[:,1])
    lims = [
        np.min([ax.get_xlim(), ax.get_ylim()]), 
        np.max([ax.get_xlim(), ax.get_ylim()]),  
    ]

    ax.plot(lims, lims, 'k-', alpha=0.75, zorder=0)
    ax.set_aspect('equal')
    ax.set_xlim(lims)
    ax.set_ylim(lims)
    ax.set_title(title)
```

**Expected behavior**
Reference and predicted energies should be almost the same.

**Desktop (please complete the following information):**
Using COLAB.

**Comment by YuuuXie** [comment]
Hi @ThePauliPrinciple 

Thanks for reporting the issue! We just checked the dataset, it seems that the energy labels used to train the model are with unit Hartree, while the forces are eV/A. That makes the training messed up. We have fixed this in the dataset and the prediction should be correct now.

**Comment by YuuuXie** [comment]
Hi @ThePauliPrinciple 
We just made the link public, could you please check again

**Comment by ThePauliPrinciple** [comment]
Works for me.
