### ISSUE TITLE
FakeMD?

### ISSUE THREAD

**Issue by lenardcarroll** [mir-group/flare#331]
Hi there, I am trying to use FakeMD as stated here: https://mir-group.github.io/flare/flare/md/fake.html#flare.md.fake.FakeMD

I can't seem to locate the class for FakeMD though, can I get some help on how to use it?

**Comment by YuuuXie** [comment]
Hi @lenardcarroll, you need to check out the `development` branch instead of the `master`. Sorry for this confusion, we will merge dev to master soon

**Comment by lenardcarroll** [comment]
Thank you very much Yu, I will check it out.
