### ISSUE TITLE
ASE_OTF missing timestep

### ISSUE THREAD

**Issue by usamaS97** [mir-group/flare#352]
Hi MIR FLARE team,

I am trying to run ASE_OTF using mir-flare==0.2.4

I am loading the following modules on my institute's HPC:
gcc/11.3.0
openblas/0.3.1
openmpi/4.1.4
pmix/3.2.3

I have attached my Python Script aswell.

I get the following error:
Traceback (most recent call last):
  File "/scratch1/usaleem/6/OTF_Pt_H1.py", line 110, in <module>
    test_otf = ASE_OTF(super_cell,
  File "/home1/usaleem/.local/lib/python3.9/site-packages/flare/ase/otf.py", line 130, in __init__
    self.md = MD(
TypeError: __init__() got an unexpected keyword argument 'timestep'

I do not get this error when running the same script on my laptop.
Note: Initially I was trying to use VASP on HPC which I thought might be causing the issue. But even switching to LJ_Calculator results in the exact same error.

Your feedback will be greatly appreciated!
[ase_otf_script.txt](https://github.com/mir-group/flare/files/11392230/ase_otf_script.txt)

**Comment by YuuuXie** [comment]
HI @usamaS97 , sorry for the delayed reply. Can you check your flare and ase versions? Using your script the on-the-fly training can run normally on my side, I can not reproduce your error. My flare version is 0.2.4 and my ase version is 3.22.1

**Comment by usamaS97** [comment]
Hi Yuu, thank you som much for reaching out. The flare version is 0.2.4. The ASE version I am using is 3.15.1. I will try with your version of ASE and let you know.

**Comment by usamaS97** [comment]
Hi @YuuuXie. Switching to ase ==3.22.1 fixes the problem. Thank you so much!
