### ISSUE TITLE
Can't run the tutorial example

### ISSUE THREAD

**Issue by FromColleWithLove** [mir-group/flare#358]
When i follow the steps from https://mir-group.github.io/flare/tutorials/gpfa.html, i get an error reading the json file of the methanol MD frames.

1.Perform the installation as described in https://mir-group.github.io/flare/installation/installation.html
2.Follow the steps 1 and 3 of the tutorial at https://mir-group.github.io/flare/tutorials/gpfa.html
3.Get the error in the python console.

I also tried running the script from a file.
I put the instructions in a .py file (named provaflare.py) , which contains:
(https://github.com/mir-group/flare/files/11819515/provaflare.txt)

```
from flare.bffs.g
p import GaussianProcess
from json import loads
from flare.atoms import FLARE_Atoms

gp = GaussianProcess(kernels=['twobody', 'threebody'],
hyps=[0.01, 0.01, 0.01, 0.01, 0.01],
cutoffs = {'twobody':7, 'threebody':3},
hyp_labels=['Two-Body Signal Variance','Two-Body Length Scale','Three-Body Signal Variance',
'Three-Body Length Scale', 'Noise Variance']
                )
with open('/path-to-flare/flare/tests/test_files/methanol_frames.json','r') as f:
        loaded_dicts = [loads(line) for line in f.readlines()]
trajectory = [FLARE_Atoms.from_dict(d) for d in loaded_dicts]


```
I then ran it with:

`python provaflare.py`
 
and got the error:

`json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 8)`

![Schermata del 2023-06-21 17-19-26](https://github.com/mir-group/flare/assets/70529115/5ed910cf-df9d-4aab-b9a4-2f5f2f05e2bf)

**Desktop **
 - OS:  Ubuntu 22.04.2 LTS x86_64

**Comment by cjowen1** [comment]
Hi Davide, all current development is being done on the ACE version of FLARE, not 2+3b. This being said, we recommend that instead of using gpfa, to use offline learning with the ACE version of FLARE as detailed in our most recent tutorial [here](https://colab.research.google.com/drive/1rZ-p3kN5CJbPJgD8HuQHSc7ecmwZYse6#scrollTo=EfjQwZwUf0Sx).
