### ISSUE TITLE
 print step information twice in  myotf_thermo.txt

### ISSUE THREAD

**Issue by YukeLi-chem** [mir-group/flare#361]
As running the example of lammps from https://github.com/mir-group/FLARE-Tutorials.git,  The step inforation is printed repeatly in . 
And OMP_NUM_THREADS is set 1.  Part of the myotf_thermo.txt as below. the  380th 390th and 400th step information are print twice:

_380_ 480.37994129420820855 5.9610221632109610113 -323.93358116283468462 -317.97255899962374315 -2256.6775499955328996 -6022.8603649484484777 -9307.5173835580153536 1169.8312402699702943 431.13341887727159474 -358.89051002954545311 0.012072248653424934653
_380_ 480.37994129420820855 5.9610221632109610113 -323.93358116283479831 -317.97255899962385683 -2256.6775499955201667 -6022.8603649484184643 -9307.5173835580117156 1169.8312402699791619 431.13341887727864332 -358.8905100295446573 0.012072248647424226042
_390_ 490.56509280594320899 6.0874094426913289979 -324.05997692235638397 -317.97256747966503099 -2362.6436669038866967 -5874.3868459463074032 -9004.0152366825022909 1208.9948171102394099 441.79380110243471336 -557.76656968536804015 0.011516272000593666749
_390_ 490.56509280594320899 6.0874094426913289979 -324.05997692235644081 -317.97256747966508783 -2362.6436669038062064 -5874.3868459462210012 -9004.0152366824313503 1208.9948171102460037 441.7938011024248226 -557.76656968538759429 0.011516271997513535114
_400_ 513.03072091789294973 6.366184836028931926 -324.33886596413105963 -317.97268112810212415 -2560.7500807494961919 -5895.892697418188618 -8686.610988280554011 1366.6397649535238088 373.75269474667214809 -607.48161562714119555 0.010144433014563546125
_400_ 513.03072091789294973 6.366184836028931926 -324.33886596413105963 -317.97268112810212415 -2560.7500807494943729 -5895.8926974181649712 -8686.6109882805121742 1366.6397649535317669 373.75269474667192071 -607.4816156271441514 0.010144433026826478114

**Comment by YuuuXie** [comment]
Hi  @YukeLi-chem, this is as expected, because every time after DFT is called, lammps is restarted from the last step before DFT, and therefore it will recalculate the last step. That is why the thermo info is printed twice. If you want to use it for post analysis, you can remove the duplicated lines and make plots
