### ISSUE TITLE
Active learning hanging there though the cores are still taken up

### ISSUE THREAD

**Issue by Teng-Martin-Ma** [mir-group/flare#365]
*Environment*
Linux OS. Built the development branch with conda.

*Issue*
Like said in title, the active learning hanged after the second DFT calculation (* Frame 1), the last output in my *.out file was uncertainty. My md engine is nosehoover in ASE and DFT calculator is VASP. The cores were still taken and no further output for tens hrs.

**Comment by YuuuXie** [comment]
@Teng-Martin-Ma , could you give more details? Are you using `GaussianProcess` or `SGP_Wrapper`? You can also attach your yaml and job submission script to let us know about your settings

**Comment by Teng-Martin-Ma** [comment]
The problem happened if using multi threads in nodes larger than 1. This issue can be closed now.
