### ISSUE TITLE
Compiling LAMMPS with KOKKOS Library Failing with FLARE 

### ISSUE THREAD

**Issue by potus28** [mir-group/flare#366]
**Describe the bug**
I am working on compiling LAMMPS with FLARE and the KOKKOS library. When pair_flare_kokkos.cpp starts to compile, the compilation fails. From the error log, it looks like the math functions cannot be found. Have you faced this error before, and if so how did you overcome it? Thanks!

**To Reproduce**
1.  Patch LAMMPS with FLARE as written in the FLARE documentation
2. Run CMake using the following directives:

-D PKG_KOKKOS=ON -D Kokkos_ENABLE_CUDA=ON -D Kokkos_ARCH_AMPERE80=on -D Kokkos_ENABLE_OPENMP=yes -D Kokkos_CXX_STANDARD=17  

3. See the error message when pair_flare_kokkos.cpp compiles

**Expected behavior**
A build of LAMMPS with FLARE that can utilize GPUs with KOKKOS.

**Screenshots**
![image](https://github.com/mir-group/flare/assets/65731874/a04ed21f-f971-43f5-b431-e9fb5cccda4e)

**Desktop (please complete the following information):**
 - NERSC's Perlmutter HPC Cluster

**Comment by anjohan** [comment]
Hi,

This is caused by the version of Kokkos bundled with LAMMPS not keeping up with Kokkos itself, and we naively pull in the newest version of KokkosKernels:
https://github.com/mir-group/flare/blob/700f2c86376a5f439483b55b7b0b2129fd0ca48e/lammps_plugins/install.sh#L51-L54

I need to find a way to automatically download the correct version of KokkosKernels, but for now, you can just add `GIT_TAG 3.7.02` to the `FetchContent` call. Either in the install script before running it, or in `lammps/CMakeLists.txt` if you've already run it.

**Comment by anjohan** [comment]
For Perlmutter specifically, you may experience that CMake doesn't find cuBLAS because it is not stored in a common location. I have had to add a flag along the lines of
```
-DCMAKE_PREFIX_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/math_libs/11.7
```
where the specific path will depend on your module. You can get a hint from `which nvcc`.

**Comment by anjohan** [comment]
Did you clean the build folder before rerunning cmake?

As for LAMMPS versions, FLARE should be compatible with the most recent versions (I tested with the LAMMPS develop branch 1-2 months ago). If the LAMMPS version were too old for FLARE itself, it would have complained about the neighbor list API.

In your version of LAMMPS, I see that the Kokkos version was 3.6, so you can try `GIT_TAG 3.6.01` (this is why I need to find a way to automatically detect the correct one).

**Comment by potus28** [comment]
Changing `GIT_TAG` to 3.6.01 did the trick thank you so much! Which file did you look in to see which Kokkos version to use?

**Comment by anjohan** [comment]
Great!

I typically just look at the commit messages in  https://github.com/lammps/lammps/tree/stable_23Jun2022/lib/kokkos, although there's also CHANGELOG.md in there.
