### ISSUE TITLE
Mapped GP Model Grid Options for SGP

### ISSUE THREAD

**Issue by usamaS97** [mir-group/flare#394]
Hi MIR Team,

I have been using FLARE to create SGP Force Fields and mapping them to LAMMPS potentials.

For the 2+3 Body GP Model offered in 0.2.4 version, the user had the option to specify the Grid Dimensions to control the fidelity of the mapped model.

I am unable to find an option to specify the fidelity of the Mapped GP file from a SGP in flare==1.4.1:

flare_calculator,_= calculator.SGP_Calculator.from_file('../Mods/B/otf_flare.json')
flare_calculator.build_map('lmp.flare', 'saleem')

Please let me know if I am missing something.

Usama Saleem
PhD Student 
University of Southern California

**Comment by YuuuXie** [comment]
Hi @usamaS97 , for the new version, it’s a different mapping mechanism for a different kernel from 2+3 body, thus it’s exact and do not need the grids any more. You can check our nature comm paper for more details

**Comment by usamaS97** [comment]
Thank you so much! Will keep that in mind!
