### ISSUE TITLE
Third unit test in test_gp_from_aimd takes forever and sometimes fails

### ISSUE THREAD

**Issue by jonpvandermause** [mir-group/flare#43]
@stevetorr could you take a look?

Here's a screenshot of the error:

![image](https://user-images.githubusercontent.com/37220876/64836491-1ab0bd80-d5b8-11e9-88b2-69efb32b9a40.png)

**Comment by stevetorr** [comment]
Sounds like there's an issue with the training. I'm looking into this. FWIW it always works on my local computer (and runs in about 10 seconds). I can push a quick fix that makes it run faster and should avert this error and look into it more soon.

**Comment by jonpvandermause** [comment]
It's actually failing every time on my machine now. Have you pulled all the updates?

**Comment by stevetorr** [comment]
This commit should speed it up:
https://github.com/mir-group/flare/commit/2622d2c4a115e914a38d8ebadaa16e8066e2cc81

While it makes the test slightly 'weaker' by no longer training the GP, other unit tests cover the act of calling and training a GP. I will open an issue to make this unit test better.

**Comment by stevetorr** [comment]
Also FWIW, it wasn't just you: I tried the offending unit test on Odyssey and it did indeed hang there. Things should all be up to date. We can take the difference between the above new commit and the current development branch to see what's wrong.

**Comment by stevetorr** [comment]
Opened a PR, thanks for bringing this to my attention. Sorry I didn't catch it sooner!
