### ISSUE TITLE
Kernel Benchmarks

### ISSUE THREAD

**Issue by dmclark17** [mir-group/flare#62]
Before trying to make any kernel optimizations, I thought it would be good to make a suite of benchmarks so we can easily and consistently measure any performance boosts. 

I am thinking a two phase benchmark would work well. 

- [ ] Setup script with constructs kernel inputs (atomic environments and the required parameters) and write them to disk in a language agnostic form. This data can then be used by multiple implementations of the kernel. 
- [ ] Python/numba implementation test which reads in the data and times the computation of the kernels

**Comment by dmclark17** [comment]
It might be good to use serialization methods mentioned in #16 and #64.

**Comment by stevetorr** [comment]
I endorse the use of the serialization methods! There's a PR up now that allows for GPs to be serialized as JSON files so we could just pass the models around:  https://github.com/mir-group/flare/pull/64

The hdf5 format could be useful for efficiency for large training data sets, but I think we can cross that bridge once we get there (such as if sparse GPs make huge training sets feasible to work with). JSON isn't the most efficient option, strictly, for storing big arrays, but they are implemented right now and allow for storing everything you need in one .json file (either for a collection of structures representing a trajectory, a set of environments processed from a structure, or an entire GP).

**Comment by jonpvandermause** [comment]
No reason we can't have both! hdf5 will be useful for the kernel acceleration that David is looking into now.

**Comment by stevetorr** [comment]
Sounds good! hdf5 isn't mission critical for me right now, so @dmclark17, feel free to assign yourself to #16 , or we can open a new issue for hdf5 serialization :)
