### ISSUE TITLE
Setup.py file would help new users

### ISSUE THREAD

**Issue by stevetorr** [mir-group/flare#66]
A setup.py file contains lots of useful info-- among other things, a list of all python packages which are required. Running this can install everything that is needed and so would be handy for new users.

One such guide to doing so is here:
https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/quickstart.html

We can include this on the wishlist for V 1.0.

**Comment by anjohan** [comment]
I also thought of this, and I can look into it (maybe next week?) unless someone else has a burning desire.

Note that I already added a requirements.txt (used by Travis) for `pip install -r requirements.txt`.

**Comment by stevetorr** [comment]
No burning desire on my end- this would be helpful. I saw the requirements.txt; thanks for that!
