### ISSUE TITLE
naming convention for new branches

### ISSUE THREAD

**Issue by jonpvandermause** [mir-group/flare#72]
This idea is courtesy of @dmclark17. To keep branches organized and easy to navigate, I propose we adhere to the following convention for naming branches:

type of change/branch owner/description of change

Some examples:
bug/jon/gp-hotfix
feature/jon/cool-new-kernel
docs/jon/env-docstrings
etc.

**Comment by stevetorr** [comment]
Great idea @dmclark17 !
