### ISSUE TITLE
VASP (potentially more)  Parser Utility Functions

### ISSUE THREAD

**Issue by stevetorr** [mir-group/flare#78]
One feature that would help to accelerate the pipeline of GP from AIMD workflows would be helper functions which parse DFT outputs (like VASP) and turn them into a file of serialized structures decorated with force information. A second helper function could generate atomic environments from a .json file. The use of functions like pymatgen for parsing would be extremely welcome here, as they have very high quality and externally maintained parsers for VASP. These wrappers would be simple to implement and useful.

Relevant to #19.

**Comment by kylebystrom** [comment]
Closed by #82
