### ISSUE TITLE
ASE virial stress & test otf_parser for its output

### ISSUE THREAD

**Issue by YuuuuXie** [mir-group/flare#86]
1. calculate stress based on atomic forces
2. test otf_parser to parser the output file from ase-otf

**Comment by nw13slx** [comment]
It may not worth the effort to add the stress calculator. It's going too deep into the force calculation. If the user really want to run something complicated like an NPT simulation, he/she should sort to our LAMMPS plug-in

**Comment by YuuuuXie** [comment]
> It may not worth the effort to add the stress calculator. It's going too deep into the force calculation. If the user really want to run something complicated like an NPT simulation, he/she should sort to our LAMMPS plug-in

Maybe we can leave it for next release

**Comment by jonpvandermause** [comment]
> It may not worth the effort to add the stress calculator. It's going too deep into the force calculation. If the user really want to run something complicated like an NPT simulation, he/she should sort to our LAMMPS plug-in

Stress is just r tensor f -- shouldn't be hard to implement. It would be valuable to be able to do on-the-fly NPT simulations, which isn't possible with the LAMMPS plug-in.

**Comment by nw13slx** [comment]
For MGP, this is straight forward. But for pure GP, this needs to go all the way back to the kernel function. We should add new njit function for atomic stress to track down which f is coming from which pair of r. This is outside of the scope of the ASE module. Maybe open another issue for the pure GP part.

**Comment by YuuuuXie** [comment]
> For MGP, this is straight forward. But for pure GP, this needs to go all the way back to the kernel function. We should add new njit function for atomic stress to track down which f is coming from which pair of r. This is outside of the scope of the ASE module. Maybe open another issue for the pure GP part.

I remember Jon ever had a stress kernel. Should we add it to the repo? @jonpvandermause

**Comment by nw13slx** [comment]
> > For MGP, this is straight forward. But for pure GP, this needs to go all the way back to the kernel function. We should add new njit function for atomic stress to track down which f is coming from which pair of r. This is outside of the scope of the ASE module. Maybe open another issue for the pure GP part.
> 
> I remember Jon ever had a stress kernel. Should we add it to the repo? @jonpvandermause

That would save a lot of work!
